export const STORAGE_KEY = "safety-first-vancouver-condo-v1";

export const HAZARD_CATEGORIES = [
  "Fall protection",
  "Housekeeping",
  "Silica / dust",
  "Electrical",
  "Crane / lift",
  "Traffic control",
  "Fire / hot work",
  "PPE",
  "Access / egress",
  "Other",
];

export const RISK_LEVELS = ["Low", "Medium", "High", "Critical"];

export const DEFICIENCY_STATUSES = [
  "Open",
  "In progress",
  "Ready for review",
  "Closed",
];

export const TRADE_OPTIONS = [
  "Concrete forming",
  "Rebar",
  "Electrical",
  "Mechanical",
  "Drywall",
  "Glazing",
  "Roofing",
  "Traffic control",
  "General contractor",
];

export const HIGH_RISK_TYPES = [
  "Fall protection",
  "Silica",
  "Confined space",
  "Hot work",
  "Crane / lift work",
  "Energization",
  "Traffic control",
];

export const HIGH_RISK_STATUSES = [
  "Needs review",
  "Ready",
  "Active",
  "Complete",
  "On hold",
];

export const TOOLBOX_TOPICS = [
  "Fall protection",
  "Silica dust control",
  "Housekeeping and access",
  "Crane and material handling",
  "Hot work fire watch",
  "Electrical energization",
  "Traffic control",
];

// Field lists keep the data model and CSV export/import aligned.
export const CSV_FIELDS = {
  deficiencies: [
    "id",
    "createdAt",
    "floorLocation",
    "tradeCompany",
    "hazardCategory",
    "riskLevel",
    "description",
    "photoPlaceholder",
    "assignedTo",
    "dueDate",
    "status",
    "closedAt",
    "closeoutNotes",
  ],
  trainingRecords: [
    "id",
    "workerName",
    "employerTrade",
    "orientationComplete",
    "fallProtectionVerified",
    "silicaTrainingVerified",
    "supervisorName",
    "expiryDate",
    "reminderDate",
    "notes",
  ],
  highRiskDocs: [
    "id",
    "type",
    "location",
    "status",
    "responsible",
    "permitRef",
    "reviewDate",
    "notes",
  ],
};

export const blankDeficiency = () => ({
  id: crypto.randomUUID(),
  createdAt: new Date().toISOString().slice(0, 10),
  floorLocation: "",
  tradeCompany: TRADE_OPTIONS[0],
  hazardCategory: HAZARD_CATEGORIES[0],
  riskLevel: "Medium",
  description: "",
  photoPlaceholder: "",
  assignedTo: "",
  dueDate: "",
  status: "Open",
  closedAt: "",
  closeoutNotes: "",
});

export const blankTrainingRecord = () => ({
  id: crypto.randomUUID(),
  workerName: "",
  employerTrade: TRADE_OPTIONS[0],
  orientationComplete: false,
  fallProtectionVerified: false,
  silicaTrainingVerified: false,
  supervisorName: "",
  expiryDate: "",
  reminderDate: "",
  notes: "",
});

export const blankHighRiskDoc = (type = HIGH_RISK_TYPES[0]) => ({
  id: crypto.randomUUID(),
  type,
  location: "",
  status: "Needs review",
  responsible: "",
  permitRef: "",
  reviewDate: "",
  notes: "",
});

export const sampleData = {
  deficiencies: [
    {
      id: "def-001",
      createdAt: "2026-06-10",
      floorLocation: "Level 18 east slab edge",
      tradeCompany: "Concrete forming",
      hazardCategory: "Fall protection",
      riskLevel: "Critical",
      description:
        "Guardrail section removed for material landing. Area needs hard barricade and supervisor sign-off before work continues.",
      photoPlaceholder: "Photo ref: L18-edge-01",
      assignedTo: "Forming foreperson",
      dueDate: "2026-06-12",
      status: "In progress",
      closedAt: "",
      closeoutNotes: "Temporary barricade installed. Awaiting permanent rail repair.",
    },
    {
      id: "def-002",
      createdAt: "2026-06-11",
      floorLocation: "Parkade P2 loading bay",
      tradeCompany: "Electrical",
      hazardCategory: "Housekeeping",
      riskLevel: "Medium",
      description:
        "Extension cords crossing pedestrian route without cable protection.",
      photoPlaceholder: "Photo ref: P2-cords-02",
      assignedTo: "Electrical lead hand",
      dueDate: "2026-06-13",
      status: "Open",
      closedAt: "",
      closeoutNotes: "",
    },
    {
      id: "def-003",
      createdAt: "2026-06-08",
      floorLocation: "Level 7 corridor rough-in",
      tradeCompany: "Mechanical",
      hazardCategory: "Silica / dust",
      riskLevel: "High",
      description:
        "Concrete drilling planned near occupied work area. Dust controls and HEPA vacuum verification needed before start.",
      photoPlaceholder: "Photo ref: L7-drill-01",
      assignedTo: "Mechanical supervisor",
      dueDate: "2026-06-09",
      status: "Ready for review",
      closedAt: "",
      closeoutNotes: "Crew submitted control plan and vacuum inspection tag.",
    },
    {
      id: "def-004",
      createdAt: "2026-06-02",
      floorLocation: "Street frontage hoist access",
      tradeCompany: "Traffic control",
      hazardCategory: "Traffic control",
      riskLevel: "High",
      description:
        "Pedestrian detour signage shifted during delivery. Reconfirm layout before afternoon concrete trucks arrive.",
      photoPlaceholder: "Photo ref: street-detour-03",
      assignedTo: "TCP supervisor",
      dueDate: "2026-06-03",
      status: "Closed",
      closedAt: "2026-06-04",
      closeoutNotes: "Signs reset and delivery gate spotter briefed.",
    },
  ],
  trainingRecords: [
    {
      id: "trn-001",
      workerName: "Worker A",
      employerTrade: "Concrete forming",
      orientationComplete: true,
      fallProtectionVerified: true,
      silicaTrainingVerified: false,
      supervisorName: "Forming foreperson",
      expiryDate: "2026-09-15",
      reminderDate: "2026-08-15",
      notes: "Sample placeholder record. No medical information.",
    },
    {
      id: "trn-002",
      workerName: "Worker B",
      employerTrade: "Electrical",
      orientationComplete: true,
      fallProtectionVerified: false,
      silicaTrainingVerified: true,
      supervisorName: "Electrical lead hand",
      expiryDate: "2026-07-20",
      reminderDate: "2026-07-01",
      notes: "Needs fall protection card verification before exposed edge work.",
    },
    {
      id: "trn-003",
      workerName: "Worker C",
      employerTrade: "Mechanical",
      orientationComplete: false,
      fallProtectionVerified: false,
      silicaTrainingVerified: true,
      supervisorName: "Mechanical supervisor",
      expiryDate: "2026-10-01",
      reminderDate: "2026-09-01",
      notes: "Orientation scheduled for next site start.",
    },
  ],
  highRiskDocs: [
    {
      id: "hr-001",
      type: "Fall protection",
      location: "Levels 16-20 perimeter",
      status: "Active",
      responsible: "CSO and forming supervisor",
      permitRef: "FP-2026-06-18",
      reviewDate: "2026-06-18",
      notes: "Review anchors, guardrails, swing stage access, and rescue plan before shift.",
    },
    {
      id: "hr-002",
      type: "Silica",
      location: "Levels 6-8 corridor coring",
      status: "Ready",
      responsible: "Mechanical supervisor",
      permitRef: "SIL-2026-06-17",
      reviewDate: "2026-06-17",
      notes: "Wet methods, HEPA vacuum, exclusion zone, and respiratory protection check.",
    },
    {
      id: "hr-003",
      type: "Confined space",
      location: "Parkade sump room",
      status: "Needs review",
      responsible: "GC superintendent",
      permitRef: "",
      reviewDate: "2026-06-19",
      notes: "Confirm classification, attendant, rescue arrangement, and air testing process.",
    },
    {
      id: "hr-004",
      type: "Hot work",
      location: "Level 3 amenity mechanical room",
      status: "On hold",
      responsible: "Mechanical supervisor",
      permitRef: "HW-2026-06-14",
      reviewDate: "2026-06-14",
      notes: "Combustibles remain in area. Fire watch not yet assigned.",
    },
    {
      id: "hr-005",
      type: "Crane / lift work",
      location: "Tower crane and loading platforms",
      status: "Active",
      responsible: "Crane coordinator",
      permitRef: "LIFT-DAILY",
      reviewDate: "2026-06-18",
      notes: "Daily lift coordination meeting complete. Wind threshold noted.",
    },
    {
      id: "hr-006",
      type: "Energization",
      location: "Main electrical room",
      status: "Ready",
      responsible: "Electrical supervisor",
      permitRef: "EN-2026-06-21",
      reviewDate: "2026-06-21",
      notes: "Confirm lockout plan, access control, and notification before energization.",
    },
    {
      id: "hr-007",
      type: "Traffic control",
      location: "Lane closure at site frontage",
      status: "Active",
      responsible: "TCP supervisor",
      permitRef: "TCP-2026-06",
      reviewDate: "2026-06-18",
      notes: "Morning setup verified. Afternoon concrete delivery window requires spotter.",
    },
  ],
};
