export const demoScenarios = [
  {
    id: "parkade-concrete-cutting",
    title: "Cutting concrete in parkade",
    input: "cutting concrete in parkade",
    packId: "concrete-cutting-silica",
    siteScanId: "parkade-dust-and-public-route",
    headline: "One dusty task becomes a source-aware field workflow.",
    presenterNotes: [
      "Start with a plain jobsite phrase, not a safety expert keyword.",
      "Show that the app assembles a talk, checklist, quiz, forms, and source links from local content.",
      "Close on the review guardrail: draft content, source review required, no legal-compliance claim.",
    ],
    riskSummary: {
      hazards: 5,
      documents: 5,
      crewActions: 4,
      sourceLinks: 8,
      timeSavedMinutes: 42,
    },
  },
  {
    id: "slab-edge-formwork",
    title: "Formwork near open slab edge",
    input: "formwork leading edge guardrail",
    packId: "formwork-leading-edge",
    siteScanId: "level-18-edge-and-material-landing",
    headline: "A fall exposure becomes a coordinated work package.",
    presenterNotes: [
      "Use this when investors ask whether the model works beyond silica.",
      "Highlight rescue planning, guardrail control, and prime contractor coordination.",
    ],
    riskSummary: {
      hazards: 5,
      documents: 4,
      crewActions: 4,
      sourceLinks: 7,
      timeSavedMinutes: 38,
    },
  },
  {
    id: "street-delivery-crane",
    title: "Street delivery and crane pick",
    input: "crane pick with pedestrian detour",
    packId: "crane-pick-rigging",
    siteScanId: "street-frontage-crane-and-detour",
    headline: "A public-interface lift becomes a controlled risk plan.",
    presenterNotes: [
      "Use this to show the connection between traffic control, cranes, rigging, and public protection.",
      "Open the risk map after this scenario to show grouped trade and area risk.",
    ],
    riskSummary: {
      hazards: 6,
      documents: 5,
      crewActions: 5,
      sourceLinks: 7,
      timeSavedMinutes: 46,
    },
  },
];

export const siteScanSamples = [
  {
    id: "parkade-dust-and-public-route",
    title: "Parkade cutting zone",
    location: "P2 parkade loading bay",
    scenario: "Concrete cutting is planned beside an active material route and temporary power.",
    packId: "concrete-cutting-silica",
    simulatedDetections: [
      {
        id: "dust-source",
        label: "Silica dust task",
        severity: "High",
        packId: "concrete-cutting-silica",
        x: 61,
        y: 45,
        note: "Wet cutting and HEPA controls need verification before the cut starts.",
      },
      {
        id: "public-route",
        label: "Pedestrian/material route",
        severity: "Medium",
        packId: "pedestrian-detour-public-protection",
        x: 30,
        y: 69,
        note: "Route crosses the work zone and needs separation or timing control.",
      },
      {
        id: "temporary-power",
        label: "Temporary power",
        severity: "Medium",
        packId: "temporary-power-extension-cords",
        x: 42,
        y: 34,
        note: "Cord routing and damage check should happen before tools start.",
      },
      {
        id: "ppe-gap",
        label: "PPE verification",
        severity: "Medium",
        packId: "respirator-fit-seal-check",
        x: 73,
        y: 65,
        note: "Respirator fit/seal and eye/face protection need crew confirmation.",
      },
      {
        id: "emergency-access",
        label: "Emergency access",
        severity: "Low",
        packId: "first-aid-room-kit-readiness",
        x: 19,
        y: 23,
        note: "Keep first aid and response route clear while the parkade is isolated.",
      },
    ],
  },
  {
    id: "level-18-edge-and-material-landing",
    title: "Level 18 edge work",
    location: "Level 18 east slab edge",
    scenario: "Formwork and material staging are happening near a guardrail change and open edge.",
    packId: "open-slab-edge-fall-protection",
    simulatedDetections: [
      {
        id: "open-edge",
        label: "Open edge",
        severity: "Critical",
        packId: "open-slab-edge-fall-protection",
        x: 70,
        y: 29,
        note: "Guardrail or tie-off plan must be confirmed before work continues.",
      },
      {
        id: "formwork-edge",
        label: "Formwork leading edge",
        severity: "Critical",
        packId: "formwork-leading-edge",
        x: 57,
        y: 58,
        note: "Sequence and control ownership need to be clear during forming and stripping.",
      },
      {
        id: "fall-rescue",
        label: "Fall rescue readiness",
        severity: "High",
        packId: "roofing-edge-work",
        x: 27,
        y: 37,
        note: "Rescue route and equipment need to be available before fall arrest is used.",
      },
      {
        id: "housekeeping",
        label: "Access route clutter",
        severity: "Medium",
        packId: "housekeeping-access-routes",
        x: 43,
        y: 78,
        note: "Stored material could hide openings or slow emergency access.",
      },
    ],
  },
  {
    id: "street-frontage-crane-and-detour",
    title: "Street frontage lift",
    location: "Street frontage and delivery gate",
    scenario: "A crane pick and delivery route overlap with pedestrian detour controls.",
    packId: "crane-pick-rigging",
    simulatedDetections: [
      {
        id: "crane-zone",
        label: "Crane pick zone",
        severity: "High",
        packId: "crane-pick-rigging",
        x: 49,
        y: 31,
        note: "Lift communication and exclusion zone must be confirmed.",
      },
      {
        id: "suspended-load",
        label: "Suspended load path",
        severity: "Critical",
        packId: "suspended-load-exclusion-zone",
        x: 65,
        y: 50,
        note: "Workers and pedestrians must be kept out of the load path.",
      },
      {
        id: "detour",
        label: "Pedestrian detour",
        severity: "High",
        packId: "pedestrian-detour-public-protection",
        x: 25,
        y: 63,
        note: "Signage and barriers need a pre-delivery check.",
      },
      {
        id: "mobile-equipment",
        label: "Delivery blind spot",
        severity: "Medium",
        packId: "mobile-equipment-deliveries",
        x: 77,
        y: 72,
        note: "Spotter and truck movement controls need to be assigned.",
      },
    ],
  },
  {
    id: "interior-hot-work-and-chemicals",
    title: "Interior hot work",
    location: "Level 7 corridor rough-in",
    scenario: "Grinding and hot work are planned near stored products, cords, and adjacent trades.",
    packId: "hot-work-fire-watch",
    simulatedDetections: [
      {
        id: "hot-work",
        label: "Hot work",
        severity: "High",
        packId: "hot-work-fire-watch",
        x: 58,
        y: 46,
        note: "Combustibles, extinguisher access, and fire watch need confirmation.",
      },
      {
        id: "chemical-storage",
        label: "Chemical storage",
        severity: "Medium",
        packId: "whmis-chemical-storage",
        x: 34,
        y: 51,
        note: "Label, SDS, compatibility, and ignition source controls need review.",
      },
      {
        id: "grinding-ppe",
        label: "Eye/face hazard",
        severity: "Medium",
        packId: "eye-face-protection-grinding",
        x: 69,
        y: 68,
        note: "Nearby workers may need protection from sparks and particles.",
      },
      {
        id: "cord-route",
        label: "Cord route",
        severity: "Medium",
        packId: "temporary-power-extension-cords",
        x: 21,
        y: 77,
        note: "Temporary power crosses a corridor and needs routing control.",
      },
    ],
  },
];

export const riskMapRecords = [
  {
    id: "risk-001",
    area: "P2 parkade",
    trade: "Concrete",
    hazard: "Silica / dust",
    urgency: "High",
    status: "Needs controls verified",
    packId: "concrete-cutting-silica",
    summary: "Concrete cutting planned near active material route.",
  },
  {
    id: "risk-002",
    area: "Level 18 east",
    trade: "Formwork",
    hazard: "Falls",
    urgency: "Critical",
    status: "Stop-work until control assigned",
    packId: "formwork-leading-edge",
    summary: "Guardrail change and leading-edge work overlap.",
  },
  {
    id: "risk-003",
    area: "Street frontage",
    trade: "Crane",
    hazard: "Suspended load",
    urgency: "Critical",
    status: "Lift plan briefing required",
    packId: "suspended-load-exclusion-zone",
    summary: "Load path intersects delivery gate and detour timing.",
  },
  {
    id: "risk-004",
    area: "Street frontage",
    trade: "Traffic control",
    hazard: "Public interface",
    urgency: "High",
    status: "Detour inspection due",
    packId: "pedestrian-detour-public-protection",
    summary: "Pedestrian signage shifted during delivery setup.",
  },
  {
    id: "risk-005",
    area: "Level 7 corridor",
    trade: "Mechanical",
    hazard: "Hot work",
    urgency: "High",
    status: "Fire watch confirmation required",
    packId: "hot-work-fire-watch",
    summary: "Grinding and torch work near stored materials.",
  },
  {
    id: "risk-006",
    area: "Level 7 corridor",
    trade: "Electrical",
    hazard: "Temporary power",
    urgency: "Medium",
    status: "Cord route correction open",
    packId: "temporary-power-extension-cords",
    summary: "Extension cords cross shared access route.",
  },
  {
    id: "risk-007",
    area: "P1 loading bay",
    trade: "Logistics",
    hazard: "Mobile equipment",
    urgency: "Medium",
    status: "Spotter briefing due",
    packId: "mobile-equipment-deliveries",
    summary: "Delivery truck backing path crosses pedestrian route.",
  },
  {
    id: "risk-008",
    area: "Roof",
    trade: "Roofing",
    hazard: "Falls",
    urgency: "Critical",
    status: "Rescue plan check due",
    packId: "roofing-edge-work",
    summary: "Roof edge material staging near open perimeter.",
  },
  {
    id: "risk-009",
    area: "Level 3 shaft",
    trade: "Mechanical",
    hazard: "Confined space",
    urgency: "High",
    status: "Entry procedure review required",
    packId: "confined-space-entry",
    summary: "Restricted access and atmospheric testing required before entry.",
  },
  {
    id: "risk-010",
    area: "Site-wide",
    trade: "General contractor",
    hazard: "New workers",
    urgency: "Medium",
    status: "Orientation follow-up open",
    packId: "new-worker-orientation",
    summary: "New subcontractor crew needs site-specific briefing.",
  },
  {
    id: "risk-011",
    area: "Level 12",
    trade: "Drywall",
    hazard: "Housekeeping",
    urgency: "Medium",
    status: "Corrective action due today",
    packId: "housekeeping-access-routes",
    summary: "Material storage narrows emergency access path.",
  },
  {
    id: "risk-012",
    area: "Site-wide",
    trade: "All trades",
    hazard: "Emergency response",
    urgency: "High",
    status: "AED and muster refresh due",
    packId: "cardiac-arrest-emergency-response",
    summary: "Crew refresh requested after emergency drill gap.",
  },
];

export function getDemoScenarioById(id) {
  return demoScenarios.find((scenario) => scenario.id === id) || null;
}

export function getSiteScanSampleById(id) {
  return siteScanSamples.find((sample) => sample.id === id) || null;
}
