// Generated by scripts/build-wiki-review-issues.js. Do not edit by hand.
export const generatedWikiReviewIssues = [
  {
    "slug": "aeds-on-construction-sites",
    "title": "AEDs on Construction Sites",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "anchor-points",
    "title": "Anchor Points",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "asbestos-basics",
    "title": "Asbestos Basics",
    "reviewTier": "Tier 1",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "carbon-monoxide",
    "title": "Carbon Monoxide",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "cardiac-arrest-on-site",
    "title": "Cardiac Arrest on Site",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "cold-stress",
    "title": "Cold Stress",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "compressed-gas-cylinders",
    "title": "Compressed Gas Cylinders",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "concrete-formwork",
    "title": "Concrete Formwork",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "concrete-pumping",
    "title": "Concrete Pumping",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "confined-space-entry",
    "title": "Confined Space Entry",
    "reviewTier": "Tier 1",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "confined-space-rescue",
    "title": "Confined Space Rescue",
    "reviewTier": "Tier 1",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "corrective-actions",
    "title": "Corrective Actions",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "crane-operator-signaller-responsibilities",
    "title": "Crane Operator/Signaller Responsibilities",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "cranes-and-hoists",
    "title": "Cranes and Hoists",
    "reviewTier": "Tier 1",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "cranes-near-power-lines",
    "title": "Cranes Near Power Lines",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "de-energization",
    "title": "De-Energization",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "demolition-planning",
    "title": "Demolition Planning",
    "reviewTier": "Tier 2",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "dust-control-methods",
    "title": "Dust Control Methods",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "electrical-safety-near-power-lines",
    "title": "Electrical Safety Near Power Lines",
    "reviewTier": "Tier 1",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "emergency-transportation",
    "title": "Emergency Transportation",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "employer-duties",
    "title": "Employer Duties",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "evacuation",
    "title": "Evacuation",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "excavation-and-trenching",
    "title": "Excavation and Trenching",
    "reviewTier": "Tier 1",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "excavation-spoil-piles",
    "title": "Excavation Spoil Piles",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "eye-and-face-protection",
    "title": "Eye and Face Protection",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "fall-arrest",
    "title": "Fall Arrest",
    "reviewTier": "Tier 1",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "fall-protection-plan",
    "title": "Fall Protection Plan",
    "reviewTier": "Tier 1",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "fall-protection",
    "title": "Fall Protection",
    "reviewTier": "Tier 1",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "fall-rescue-plan",
    "title": "Fall Rescue Plan",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "fall-restraint",
    "title": "Fall Restraint",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "falsework",
    "title": "Falsework",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "fire-extinguishers",
    "title": "Fire Extinguishers",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "fire-prevention-plan",
    "title": "Fire Prevention Plan",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "first-aid-assessment",
    "title": "First Aid Assessment",
    "reviewTier": "Tier 2",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "first-aid-room",
    "title": "First Aid Room",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "floor-openings-and-covers",
    "title": "Floor Openings and Covers",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "gloves",
    "title": "Gloves",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "guardrails",
    "title": "Guardrails",
    "reviewTier": "Tier 1",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "hard-hats",
    "title": "Hard Hats",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "hazardous-materials-before-demolition",
    "title": "Hazardous Materials Before Demolition",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "hearing-protection",
    "title": "Hearing Protection",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "heat-stress",
    "title": "Heat Stress",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "hepa-vacuums",
    "title": "HEPA Vacuums",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "high-visibility-apparel",
    "title": "High Visibility Apparel",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "hoarding-and-public-protection",
    "title": "Hoarding and Public Protection",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "hot-work",
    "title": "Hot Work",
    "reviewTier": "Tier 2",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "housekeeping",
    "title": "Housekeeping",
    "reviewTier": "Tier 2",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "incident-investigation",
    "title": "Incident Investigation",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "jhsc-requirements",
    "title": "JHSC Requirements",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "ladder-inspection",
    "title": "Ladder Inspection",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "ladders",
    "title": "Ladders",
    "reviewTier": "Tier 2",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "lead-exposure-control",
    "title": "Lead Exposure Control",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "leading-edge-work",
    "title": "Leading Edge Work",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "lift-plans",
    "title": "Lift Plans",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "lockout",
    "title": "Lockout",
    "reviewTier": "Tier 2",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "material-handling",
    "title": "Material Handling",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "mobile-elevating-work-platforms",
    "title": "Mobile Elevating Work Platforms",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "mobile-equipment",
    "title": "Mobile Equipment",
    "reviewTier": "Tier 2",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "mould-in-restoration",
    "title": "Mould in Restoration",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "noise-exposure",
    "title": "Noise Exposure",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "notice-of-project",
    "title": "Notice of Project",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "occupational-first-aid-requirements",
    "title": "Occupational First Aid Requirements",
    "reviewTier": "Tier 1",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "ohs-program",
    "title": "OHS Program",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "powder-actuated-tools",
    "title": "Powder-Actuated Tools",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "power-tools",
    "title": "Power Tools",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "ppe-basics",
    "title": "PPE Basics",
    "reviewTier": "Tier 2",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "prime-contractor-duties",
    "title": "Prime Contractor Duties",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "rebar-impalement-protection",
    "title": "Rebar Impalement Protection",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "refusal-of-unsafe-work",
    "title": "Refusal of Unsafe Work",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "respirators",
    "title": "Respirators",
    "reviewTier": "Tier 1",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "rigging-basics",
    "title": "Rigging Basics",
    "reviewTier": "Tier 1",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "roof-work",
    "title": "Roof Work",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "rope-access",
    "title": "Rope Access",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "safety-footwear",
    "title": "Safety Footwear",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "scaffold-inspection",
    "title": "Scaffold Inspection",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "scaffolds",
    "title": "Scaffolds",
    "reviewTier": "Tier 2",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "serious-injury-reporting",
    "title": "Serious Injury Reporting",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "silica-exposure-control",
    "title": "Silica Exposure Control",
    "reviewTier": "Tier 1",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "site-emergency-response-plan",
    "title": "Site Emergency Response Plan",
    "reviewTier": "Tier 2",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "site-orientation",
    "title": "Site Orientation",
    "reviewTier": "Tier 2",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "site-specific-safety-plan",
    "title": "Site-Specific Safety Plan",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "supervisor-duties",
    "title": "Supervisor Duties",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "suspension-trauma",
    "title": "Suspension Trauma",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "swing-stages",
    "title": "Swing Stages",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "temporary-power",
    "title": "Temporary Power",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "tilt-up-construction",
    "title": "Tilt-Up Construction",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "toolbox-talks",
    "title": "Toolbox Talks",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "traffic-control-persons",
    "title": "Traffic Control Persons",
    "reviewTier": "Tier 2",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "traffic-control-plans",
    "title": "Traffic Control Plans",
    "reviewTier": "Tier 2",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "traffic-control",
    "title": "Traffic Control",
    "reviewTier": "Tier 1",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 1,
    "issues": [
      {
        "id": "traffic-control:legalRequirements:8",
        "articleSlug": "traffic-control",
        "articleTitle": "Traffic Control",
        "articlePath": "/wiki/articles/traffic-control",
        "reviewTier": "Tier 1",
        "section": "legalRequirements",
        "sectionTitle": "Legal requirements",
        "index": 8,
        "contextAnchor": "review-issue-traffic-control-legalRequirements-8",
        "statement": "Confirm whether the road owner, municipality, or Ministry of Transportation and Infrastructure requires a permit, approved traffic management plan, or additional road-use condition for the specific road.",
        "originalText": "Confirm whether the road owner, municipality, or Ministry of Transportation and Infrastructure requires a permit, approved traffic management plan, or additional road-use condition for the specific road. Reviewer question: identify the correct road-authority source for permit or approval requirements, or move this item to site-specific best practice if no single BC-wide source applies. {{review:source}}",
        "beforeText": "Use traffic control persons who have completed the required traffic control person training, and apply the Traffic Management Manual requirements that Part 18 makes applicable to work zones. [ohsr-18-3] [ohsr-18-6-2]",
        "afterText": "",
        "contextText": "Use traffic control persons who have completed the required traffic control person training, and apply the Traffic Management Manual requirements that Part 18 makes applicable to work zones. [ohsr-18-3] [ohsr-18-6-2] Confirm whether the road owner, municipality, or Ministry of Transportation and Infrastructure requires a permit, approved traffic management plan, or additional road-use condition for the specific road.",
        "question": "identify the correct road-authority source for permit or approval requirements, or move this item to site-specific best practice if no single BC-wide source applies.",
        "reason": "AI could not tie this claim to an exact official citation with enough confidence.",
        "citationIds": [],
        "citations": [],
        "sourceNotes": [
          {
            "id": "source-note-worksafebc-ohs-guidelines",
            "title": "WorkSafeBC OHS Guidelines",
            "publisher": "WorkSafeBC",
            "url": "https://www.worksafebc.com/en/law-policy/occupational-health-safety/searchable-ohs-regulation/ohs-guidelines",
            "lastChecked": "2026-06-20"
          },
          {
            "id": "source-note-worksafebc-ohs-regulation",
            "title": "WorkSafeBC OHS Regulation",
            "publisher": "WorkSafeBC",
            "url": "https://www.worksafebc.com/en/law-policy/occupational-health-safety/searchable-ohs-regulation",
            "lastChecked": "2026-06-20"
          },
          {
            "id": "worksafebc-ohsr-part-16",
            "title": "WorkSafeBC OHS Regulation Part 16: Mobile Equipment",
            "publisher": "WorkSafeBC",
            "url": "https://www.worksafebc.com/en/law-policy/occupational-health-safety/searchable-ohs-regulation/ohs-regulation/part-16-mobile-equipment",
            "lastChecked": "2026-06-20"
          },
          {
            "id": "worksafebc-ohsr-part-18",
            "title": "WorkSafeBC OHS Regulation Part 18: Traffic Control",
            "publisher": "WorkSafeBC",
            "url": "https://www.worksafebc.com/en/law-policy/occupational-health-safety/searchable-ohs-regulation/ohs-regulation/part-18-traffic-control",
            "lastChecked": "2026-06-20"
          },
          {
            "id": "worksafebc-ohsr-part-8",
            "title": "WorkSafeBC OHS Regulation Part 8: Personal Protective Clothing and Equipment",
            "publisher": "WorkSafeBC",
            "url": "https://www.worksafebc.com/en/law-policy/occupational-health-safety/searchable-ohs-regulation/ohs-regulation/part-08-personal-protective-clothing-and-equipment",
            "lastChecked": "2026-06-20"
          }
        ]
      }
    ]
  },
  {
    "slug": "training-records",
    "title": "Training Records",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "underground-utilities",
    "title": "Underground Utilities",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "ventilation",
    "title": "Ventilation",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "welding-and-cutting",
    "title": "Welding and Cutting",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "wet-cutting",
    "title": "Wet Cutting",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "whmis-basics",
    "title": "WHMIS Basics",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "work-platforms",
    "title": "Work Platforms",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "worker-rights-and-responsibilities",
    "title": "Worker Rights and Responsibilities",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "workplace-inspections",
    "title": "Workplace Inspections",
    "reviewTier": "Tier 2",
    "maturity": "Draft",
    "prepStatus": "Needs human source review",
    "issueCount": 0,
    "issues": []
  },
  {
    "slug": "young-new-worker-orientation",
    "title": "Young/New Worker Orientation",
    "reviewTier": "Tier 3",
    "maturity": "Draft",
    "prepStatus": "AI source-prepped",
    "issueCount": 0,
    "issues": []
  }
];
