const coreSafetyPacks = [
  {
    id: "concrete-cutting-silica",
    title: "Concrete cutting / silica dust",
    scenario: "Cutting, grinding, coring, or drilling concrete in a parkade, suite, corridor, or other enclosed work area.",
    demoQuery: "cutting concrete in parkade",
    keywords: [
      "cutting concrete",
      "concrete cutting",
      "parkade",
      "silica",
      "dust",
      "grinding",
      "core drilling",
      "saw cutting",
      "hepa",
      "respirator",
      "wet cutting",
      "concrete drilling",
    ],
    hazards: [
      "Respirable crystalline silica",
      "Visible dust migration",
      "Respirator or fit-check gaps",
      "Noise, eye, and face exposure",
      "Poor cleanup or dry sweeping",
    ],
    requiredDocuments: [
      "Silica exposure control plan or reviewed task procedure",
      "Tool and dust-control setup check",
      "Respirator and PPE verification where required",
      "Toolbox talk attendance record",
      "Deficiency or hazard report if controls are missing",
    ],
    wikiSlugs: ["silica-exposure-control", "respirators", "whmis-basics", "site-emergency-response-plan"],
    toolboxTalkIds: ["silica-dust-controls", "wet-cutting-and-hepa-cleanup", "respirator-fit-and-seal-checks"],
    checklistIds: ["silica-dust", "ppe", "daily-site-inspection"],
    quizIds: ["silica-and-dust-quiz", "ppe-quiz"],
    formIds: ["hazard-report", "site-safety-inspection", "toolbox-talk-attendance"],
    printableSections: [
      "Confirm the exact dust-generating task, tool, work area, and affected nearby crews.",
      "Verify water delivery, HEPA vacuum capture, isolation, ventilation, and cleanup method before cutting starts.",
      "Stop the task if dust becomes visible outside the controlled work area or cleanup shifts to dry sweeping.",
      "Record the talk, checklist findings, deficiencies, and source-review status with the safety pack.",
    ],
    reviewNotice:
      "Draft safety pack only. Verify current WorkSafeBC silica requirements, exposure-control details, respirator requirements, and site-specific procedure before field use.",
  },
  {
    id: "open-slab-edge-fall-protection",
    title: "Open slab edge / fall protection",
    scenario: "Work near an open slab edge, floor opening, guardrail gap, roof edge, leading edge, or temporary material landing.",
    demoQuery: "tie off at open slab edge",
    keywords: [
      "tie off",
      "tie-off",
      "slab edge",
      "open edge",
      "fall protection",
      "fall arrest",
      "fall restraint",
      "guardrail",
      "hole cover",
      "anchor point",
      "leading edge",
      "rescue plan",
    ],
    hazards: [
      "Unprotected edge or opening",
      "Removed guardrail or cover",
      "Unverified anchor or connector",
      "Swing-fall exposure",
      "No prompt rescue method",
    ],
    requiredDocuments: [
      "Fall protection plan where required by the work",
      "Anchor, equipment, and harness inspection notes",
      "Rescue plan for fall arrest use",
      "Toolbox talk attendance record",
      "Hazard report if guards, covers, or anchors are not ready",
    ],
    wikiSlugs: [
      "fall-protection",
      "fall-protection-plan",
      "fall-arrest",
      "fall-restraint",
      "guardrails",
      "anchor-points",
      "fall-rescue-plan",
    ],
    toolboxTalkIds: [
      "tie-off-planning-before-edge-work",
      "guardrails-and-floor-openings",
      "fall-rescue-readiness",
      "harness-inspection",
    ],
    checklistIds: ["fall-protection", "daily-site-inspection"],
    quizIds: ["fall-protection-quiz"],
    formIds: ["hazard-report", "site-safety-inspection", "toolbox-talk-attendance"],
    printableSections: [
      "Walk the work area and identify the exact edge, opening, access path, and landing zone.",
      "Confirm the control method: guardrail, cover, restraint, fall arrest, or another reviewed control.",
      "Point out anchors, travel limits, rescue equipment, and who can stop the work.",
      "Document any missing guardrail, loose cover, or unverified anchor before workers enter the exposure.",
    ],
    reviewNotice:
      "Draft safety pack only. Verify current WorkSafeBC fall protection requirements, rescue planning, equipment use, and site-specific fall protection plan before field use.",
  },
  {
    id: "excavation-trenching",
    title: "Excavation and trenching",
    scenario: "Digging, entering, or working beside an excavation, trench, utility cut, service connection, or shored work area.",
    demoQuery: "trench entry near utilities",
    keywords: [
      "excavation",
      "trench",
      "trenching",
      "utility",
      "utilities",
      "shoring",
      "sloping",
      "shielding",
      "cave in",
      "cave-in",
      "spoil pile",
      "underground",
    ],
    hazards: [
      "Cave-in or sloughing",
      "Underground utility contact",
      "Equipment loading near the edge",
      "Water, vibration, or changing soil conditions",
      "Poor access or emergency egress",
    ],
    requiredDocuments: [
      "Excavation or trench review notes",
      "Utility locate or service confirmation records",
      "Protective system and access plan where required",
      "Traffic or mobile equipment control notes",
      "Emergency response contacts and rescue restrictions",
    ],
    wikiSlugs: ["excavation-and-trenching", "mobile-equipment", "traffic-control", "site-emergency-response-plan"],
    toolboxTalkIds: ["trench-cave-in-warning-signs", "underground-utility-awareness", "mobile-equipment-blind-spots"],
    checklistIds: ["excavations", "traffic-control", "emergency-response"],
    quizIds: ["excavation-and-trenching-quiz", "mobile-equipment-quiz"],
    formIds: ["hazard-report", "site-safety-inspection", "near-miss-report"],
    printableSections: [
      "Confirm soil, water, weather, utility, spoil pile, access, and equipment-loading conditions before entry.",
      "Verify protective systems and keep workers out until competent review is complete.",
      "Keep equipment, materials, and pedestrians controlled around the excavation edge.",
      "Stop work if cracking, sloughing, water, vibration, or utility uncertainty appears.",
    ],
    reviewNotice:
      "Draft safety pack only. Verify current WorkSafeBC excavation requirements, utility procedures, protective-system needs, and any engineered instructions before field use.",
  },
  {
    id: "confined-space-entry",
    title: "Confined space entry",
    scenario: "Entry into a vault, tank, sump, pit, manhole, shaft, crawl space, or other space with restricted access or atmospheric risk.",
    demoQuery: "confined space entry",
    keywords: [
      "confined space",
      "confined",
      "atmospheric test",
      "gas test",
      "vault",
      "tank",
      "sump",
      "pit",
      "manhole",
      "rescue",
      "ventilation",
      "entry permit",
    ],
    hazards: [
      "Oxygen deficiency or enrichment",
      "Toxic or flammable atmosphere",
      "Engulfment or restricted rescue access",
      "Uncontrolled energy or adjacent work",
      "Unplanned entry by unassigned workers",
    ],
    requiredDocuments: [
      "Confined space assessment and entry procedure",
      "Atmospheric testing and ventilation records",
      "Rescue plan and standby worker assignment",
      "Lockout or isolation records where needed",
      "Entry authorization and communication plan",
    ],
    wikiSlugs: [
      "confined-space-entry",
      "confined-space-rescue",
      "occupational-first-aid-requirements",
      "site-emergency-response-plan",
      "respirators",
    ],
    toolboxTalkIds: ["confined-space-entry-basics", "atmospheric-testing-awareness", "first-aid-access-and-reporting"],
    checklistIds: ["confined-space-pre-entry", "emergency-response"],
    quizIds: ["confined-spaces-quiz", "first-aid-quiz"],
    formIds: ["hazard-report", "incident-report", "toolbox-talk-attendance"],
    printableSections: [
      "Confirm the space classification, entry reason, assigned workers, and no-go conditions.",
      "Verify testing, ventilation, isolation, communication, standby, and rescue arrangements before entry.",
      "Keep the entry record current as conditions, workers, or nearby tasks change.",
      "Stop entry if testing, communication, ventilation, rescue, or supervision is interrupted.",
    ],
    reviewNotice:
      "Draft safety pack only. Verify current WorkSafeBC confined space requirements, rescue plan, atmospheric testing, and site-specific entry procedures before field use.",
  },
  {
    id: "crane-pick-rigging",
    title: "Crane pick / rigging",
    scenario: "Planning or performing a crane pick, hoist lift, rigged material movement, suspended load, or delivery lift.",
    demoQuery: "crane pick with rigging",
    keywords: [
      "crane pick",
      "crane",
      "hoist",
      "rigging",
      "suspended load",
      "lift plan",
      "signal",
      "tag line",
      "load chart",
      "exclusion zone",
      "slinger",
      "rigger",
    ],
    hazards: [
      "Suspended load over workers",
      "Poor signal or radio communication",
      "Damaged or mismatched rigging",
      "Load path conflict with pedestrians or equipment",
      "Weather, visibility, or ground condition changes",
    ],
    requiredDocuments: [
      "Lift plan or reviewed hoisting procedure where required",
      "Rigging and equipment inspection notes",
      "Signal, radio, and exclusion zone briefing",
      "Traffic or delivery control plan where relevant",
      "Toolbox talk attendance record",
    ],
    wikiSlugs: ["cranes-and-hoists", "rigging-basics", "mobile-equipment", "traffic-control"],
    toolboxTalkIds: [
      "crane-pick-communication",
      "rigging-inspection-basics",
      "exclusion-zones-under-suspended-loads",
      "spotter-communication",
    ],
    checklistIds: ["mobile-equipment", "daily-site-inspection", "ppe"],
    quizIds: ["cranes-rigging-quiz", "mobile-equipment-quiz"],
    formIds: ["equipment-inspection", "hazard-report", "toolbox-talk-attendance"],
    printableSections: [
      "Confirm the load, rigging method, travel path, exclusion zone, signal method, and stop-work authority.",
      "Inspect rigging and confirm workers understand the no-go area under and around the load.",
      "Pause the lift if communication, visibility, wind, ground conditions, or the load path changes.",
      "Record inspection notes, briefing completion, and any blocked access or interference.",
    ],
    reviewNotice:
      "Draft safety pack only. Verify current WorkSafeBC crane, hoist, rigging, certification, inspection, and lift-planning requirements before field use.",
  },
  {
    id: "hot-work-fire-watch",
    title: "Hot work / fire watch",
    scenario: "Welding, grinding, torch work, cutting, soldering, or other spark/heat-producing work near combustibles or shared work areas.",
    demoQuery: "hot work fire watch",
    keywords: [
      "hot work",
      "fire watch",
      "welding",
      "grinding sparks",
      "torch",
      "cutting",
      "combustible",
      "fire extinguisher",
      "flammable",
      "gas cylinder",
      "spark",
    ],
    hazards: [
      "Ignition of combustibles",
      "Inadequate fire watch or extinguisher access",
      "Poor cylinder, hose, or regulator condition",
      "Smoke, fumes, or ventilation gaps",
      "Adjacent workers not warned about sparks or heat",
    ],
    requiredDocuments: [
      "Hot work permit or reviewed hot work authorization where used",
      "Fire watch and post-work monitoring notes",
      "Extinguisher and combustible-control check",
      "WHMIS/SDS review for products involved",
      "Toolbox talk attendance record",
    ],
    wikiSlugs: ["site-emergency-response-plan", "whmis-basics", "occupational-first-aid-requirements", "electrical-safety-near-power-lines"],
    toolboxTalkIds: ["hot-work-fire-watch", "fire-extinguisher-access", "chemical-storage-on-site", "extension-cords-and-temporary-power"],
    checklistIds: ["hot-work", "emergency-response", "whmis-sds"],
    quizIds: ["emergency-response-quiz", "whmis-sds-quiz", "electrical-safety-quiz"],
    formIds: ["hazard-report", "site-safety-inspection", "toolbox-talk-attendance"],
    printableSections: [
      "Clear or protect combustibles, check openings, and confirm extinguisher access before hot work starts.",
      "Assign fire watch and confirm post-work monitoring expectations.",
      "Control cylinders, hoses, power cords, ventilation, and nearby pedestrian exposure.",
      "Stop work if fire watch, extinguishers, ventilation, or combustible controls are not in place.",
    ],
    reviewNotice:
      "Draft safety pack only. Verify current WorkSafeBC fire prevention, WHMIS, ventilation, hot work, and site emergency requirements before field use.",
  },
  {
    id: "mobile-equipment-deliveries",
    title: "Mobile equipment and deliveries",
    scenario: "Forklift, telehandler, skid steer, loader, delivery truck, concrete truck, or other mobile equipment moving near workers or the public.",
    demoQuery: "mobile equipment delivery gate",
    keywords: [
      "mobile equipment",
      "delivery",
      "truck",
      "forklift",
      "telehandler",
      "loader",
      "skid steer",
      "spotter",
      "blind spot",
      "backing",
      "traffic control",
      "pedestrian detour",
    ],
    hazards: [
      "Blind spots and backing equipment",
      "Pedestrian or public interface",
      "Unclear spotter signals",
      "Seat belt or rollover risk",
      "Congested access and delivery routes",
    ],
    requiredDocuments: [
      "Traffic or delivery control notes",
      "Equipment inspection record where used",
      "Spotter and communication briefing",
      "Public protection or pedestrian detour check",
      "Hazard report for route conflicts",
    ],
    wikiSlugs: ["mobile-equipment", "traffic-control", "site-orientation", "site-emergency-response-plan"],
    toolboxTalkIds: [
      "mobile-equipment-blind-spots",
      "spotter-communication",
      "traffic-control-around-deliveries",
      "pedestrian-detours",
      "seat-belts-and-rollover-risk",
    ],
    checklistIds: ["mobile-equipment", "traffic-control", "daily-site-inspection"],
    quizIds: ["mobile-equipment-quiz", "traffic-control-quiz"],
    formIds: ["equipment-inspection", "hazard-report", "site-safety-inspection"],
    printableSections: [
      "Walk the delivery route and identify workers, public access, backing zones, blind spots, and pinch points.",
      "Confirm spotter signals, radio use, exclusion areas, and who controls the gate or pedestrian hold.",
      "Inspect equipment condition and pause movement if route conditions change.",
      "Document route deficiencies, damaged controls, or public-interface concerns.",
    ],
    reviewNotice:
      "Draft safety pack only. Verify current WorkSafeBC mobile equipment, traffic control, public protection, and operator competency requirements before field use.",
  },
  {
    id: "scaffold-ladder-access",
    title: "Scaffold or ladder access",
    scenario: "Using ladders, rolling scaffolds, frame scaffolds, temporary access, or elevated work platforms for access or light work.",
    demoQuery: "scaffold ladder access",
    keywords: [
      "ladder",
      "ladders",
      "scaffold",
      "scaffolds",
      "rolling scaffold",
      "access",
      "three point contact",
      "platform",
      "tag",
      "guardrail",
      "plank",
    ],
    hazards: [
      "Unstable ladder setup",
      "Missing scaffold components",
      "Unauthorized scaffold changes",
      "Falls from access or platform edges",
      "Rolling scaffold movement with workers or loose material",
    ],
    requiredDocuments: [
      "Scaffold status or inspection record where used",
      "Ladder or access inspection notes",
      "Fall protection review where exposure exists",
      "Toolbox talk attendance record",
      "Equipment deficiency report if components are damaged or missing",
    ],
    wikiSlugs: ["ladders", "scaffolds", "fall-protection", "guardrails"],
    toolboxTalkIds: [
      "ladder-setup-and-three-point-contact",
      "scaffold-access-and-tagging",
      "rolling-scaffold-movement",
      "guardrails-and-floor-openings",
    ],
    checklistIds: ["ladders", "scaffolds", "fall-protection"],
    quizIds: ["ladders-and-scaffolds-quiz", "fall-protection-quiz"],
    formIds: ["equipment-inspection", "site-safety-inspection", "toolbox-talk-attendance"],
    printableSections: [
      "Choose the right access method for the task, height, duration, material handling, and work surface.",
      "Inspect ladder feet, top support, scaffold tag/status, guardrails, planks, ties, and access points.",
      "Keep workers off damaged, incomplete, untagged, unstable, or unauthorized access equipment.",
      "Document missing components, changed setups, and who is responsible for correction.",
    ],
    reviewNotice:
      "Draft safety pack only. Verify current WorkSafeBC ladder, scaffold, access, and fall protection requirements before field use.",
  },
  {
    id: "new-worker-orientation",
    title: "New worker orientation",
    scenario: "A new, young, transferred, returning, or subcontracted worker starts on site or changes tasks, supervisors, or work areas.",
    demoQuery: "new worker orientation",
    keywords: [
      "new worker",
      "young worker",
      "orientation",
      "site orientation",
      "subcontractor",
      "training",
      "first day",
      "rights",
      "refuse unsafe work",
      "whmis",
      "ppe",
    ],
    hazards: [
      "Worker unfamiliar with site-specific hazards",
      "Unclear supervision or stop-work process",
      "Missing PPE, WHMIS, or task-specific training",
      "No emergency route or first aid awareness",
      "Young/new worker questions not encouraged",
    ],
    requiredDocuments: [
      "Worker orientation form",
      "Training matrix or verification notes",
      "Subcontractor onboarding record where relevant",
      "Emergency response and first aid briefing",
      "Task-specific safety talk or checklist before assignment",
    ],
    wikiSlugs: ["site-orientation", "occupational-first-aid-requirements", "fall-protection", "whmis-basics", "incident-investigation"],
    toolboxTalkIds: [
      "new-worker-questions",
      "site-orientation-refresh",
      "refusing-unsafe-work",
      "first-aid-access-and-reporting",
      "whmis-labels-and-sds-access",
    ],
    checklistIds: ["daily-site-inspection", "ppe", "whmis-sds", "emergency-response"],
    quizIds: ["site-orientation-quiz", "young-new-workers-quiz", "refusing-unsafe-work-quiz"],
    formIds: ["worker-orientation", "subcontractor-safety-onboarding", "training-matrix"],
    printableSections: [
      "Confirm the worker's employer, supervisor, task, work area, emergency contacts, and site rules.",
      "Review worker rights, stop-work expectations, first aid, emergency routes, PPE, WHMIS/SDS, and reporting.",
      "Assign direct supervision and task-specific instruction before high-risk or unfamiliar work starts.",
      "Record orientation, gaps, restrictions, and follow-up verification dates.",
    ],
    reviewNotice:
      "Draft safety pack only. Verify current WorkSafeBC young/new worker orientation, training, supervision, and employer documentation requirements before field use.",
  },
  {
    id: "cardiac-arrest-emergency-response",
    title: "Cardiac arrest / emergency response",
    scenario: "A worker collapses, is unresponsive, has abnormal breathing, or a crew needs a rapid first aid, AED, muster, and emergency-access refresher.",
    demoQuery: "cardiac arrest on site",
    keywords: [
      "cardiac arrest",
      "aed",
      "first aid",
      "emergency",
      "collapse",
      "unresponsive",
      "muster",
      "headcount",
      "911",
      "ambulance",
      "rescue",
    ],
    hazards: [
      "Delayed first aid activation",
      "AED not found quickly",
      "Blocked emergency access",
      "Poor muster or headcount control",
      "Unclear incident reporting and witness notes",
    ],
    requiredDocuments: [
      "Emergency response plan or site emergency procedure",
      "First aid location and AED check",
      "Muster and access route confirmation",
      "Incident report and witness statement if an event occurs",
      "Post-event corrective action or debrief notes",
    ],
    wikiSlugs: ["cardiac-arrest-on-site", "occupational-first-aid-requirements", "site-emergency-response-plan", "incident-investigation"],
    toolboxTalkIds: [
      "cardiac-arrest-response-basics",
      "aed-location-and-emergency-access",
      "emergency-muster-and-headcount",
      "first-aid-access-and-reporting",
    ],
    checklistIds: ["emergency-response", "first-aid-kit-first-aid-room"],
    quizIds: ["first-aid-quiz", "emergency-response-quiz"],
    formIds: ["incident-report", "investigation-witness-statement", "near-miss-report"],
    printableSections: [
      "Show the crew where first aid, AED, emergency access, and muster points are located.",
      "Confirm who calls emergency services, who meets responders, and who controls the work area.",
      "Do not turn the pack into medical instruction beyond the reviewed site emergency procedure and trained first aid response.",
      "Record incident facts, witnesses, corrective actions, and source-review status after the event.",
    ],
    reviewNotice:
      "Draft safety pack only. Verify current WorkSafeBC first aid requirements and site emergency procedures. This pack is not medical advice or a substitute for trained first aid response.",
  },
];

const supplementalSafetyPacks = [
  {
    id: "power-tool-guarding",
    title: "Power tool guarding",
    scenario: "Using grinders, saws, drills, powder-actuated tools, or other powered tools that can cut, strike, kick back, or throw debris.",
    demoQuery: "grinder guard removed",
    keywords: ["power tool", "grinder", "guard", "saw", "kickback", "tool guard", "cutting wheel", "powder actuated", "drill", "flying debris"],
    hazards: ["Missing or modified guards", "Kickback and line-of-fire exposure", "Flying particles", "Noise and vibration", "Damaged cords or tool bodies"],
    requiredDocuments: ["Tool inspection record where used", "PPE and eye/face protection check", "Equipment deficiency report for damaged tools", "Toolbox talk attendance record"],
    wikiSlugs: ["electrical-safety-near-power-lines", "whmis-basics", "site-orientation"],
    toolboxTalkIds: ["power-tool-guards", "eye-and-face-protection", "hearing-protection", "extension-cords-and-temporary-power"],
    checklistIds: ["power-tools", "ppe", "daily-site-inspection"],
    quizIds: ["tool-and-equipment-safety-quiz", "ppe-quiz"],
    formIds: ["equipment-inspection", "hazard-report", "toolbox-talk-attendance"],
    printableSections: ["Confirm guards, handles, wheels, bits, cords, and switches are intact before use.", "Match eye, face, hearing, and hand protection to the tool hazard.", "Keep workers out of the line of fire and stop work if a guard is removed or bypassed.", "Record damaged tools and remove them from service."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC tool, PPE, guarding, and manufacturer instruction requirements before field use.",
  },
  {
    id: "temporary-power-extension-cords",
    title: "Temporary power and extension cords",
    scenario: "Running cords, temporary power, chargers, lights, or portable equipment through work areas, corridors, parkades, or wet locations.",
    demoQuery: "extension cords across corridor",
    keywords: ["temporary power", "extension cord", "cords", "charger", "temporary lighting", "wet location", "trip hazard", "electrical", "gfci"],
    hazards: ["Damaged cords", "Trip hazards through access routes", "Wet or unsuitable locations", "Overloaded circuits", "Unprotected temporary wiring"],
    requiredDocuments: ["Electrical deficiency or hazard report", "Daily site inspection notes", "Equipment inspection record where used", "Toolbox talk attendance record"],
    wikiSlugs: ["electrical-safety-near-power-lines", "site-orientation", "incident-investigation"],
    toolboxTalkIds: ["extension-cords-and-temporary-power", "housekeeping-and-access-routes", "power-tool-guards"],
    checklistIds: ["power-tools", "housekeeping", "daily-site-inspection"],
    quizIds: ["electrical-safety-quiz", "tool-and-equipment-safety-quiz"],
    formIds: ["hazard-report", "equipment-inspection", "site-safety-inspection"],
    printableSections: ["Inspect cords and temporary power before use.", "Route cords away from pedestrian paths, water, pinch points, and vehicle movement.", "Do not tape over damaged cords or overload temporary power setups.", "Record and correct cord routing or equipment defects."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC electrical safety, temporary power, and manufacturer instruction requirements before field use.",
  },
  {
    id: "overhead-power-line-work",
    title: "Overhead power line work area",
    scenario: "Cranes, lifts, ladders, scaffolds, trucks, concrete pump booms, or materials are used near overhead electrical lines.",
    demoQuery: "boom truck near overhead power line",
    keywords: ["overhead power", "power line", "boom", "crane near power", "ladder near power", "electrical line", "clearance", "utility"],
    hazards: ["Contact with energized lines", "Induced or arcing electrical energy", "Uncontrolled equipment movement", "Spotter communication failure", "Public or worker access to the danger zone"],
    requiredDocuments: ["Power line hazard assessment", "Utility contact or control confirmation where required", "Equipment movement plan", "Spotter and exclusion zone briefing"],
    wikiSlugs: ["electrical-safety-near-power-lines", "cranes-and-hoists", "mobile-equipment", "traffic-control"],
    toolboxTalkIds: ["overhead-power-line-awareness", "crane-pick-communication", "spotter-communication"],
    checklistIds: ["mobile-equipment", "traffic-control", "daily-site-inspection"],
    quizIds: ["electrical-safety-quiz", "cranes-rigging-quiz", "mobile-equipment-quiz"],
    formIds: ["hazard-report", "site-safety-inspection", "toolbox-talk-attendance"],
    printableSections: ["Identify line location, voltage uncertainty, equipment path, and minimum approach controls before work starts.", "Brief operators, spotters, and nearby workers on exclusion zones and stop signals.", "Stop work if equipment path, weather, visibility, or line controls change.", "Document utility controls and any blocked access or public-interface risks."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC electrical line clearance and utility-control requirements before field use.",
  },
  {
    id: "lockout-stored-energy",
    title: "Lockout and stored energy",
    scenario: "Maintenance, clearing jams, changing blades, servicing pumps, or working on equipment with electrical, hydraulic, pneumatic, gravity, thermal, or stored-pressure energy.",
    demoQuery: "lockout before maintenance",
    keywords: ["lockout", "tagout", "stored energy", "maintenance", "energization", "hydraulic", "pneumatic", "gravity", "pressure", "jam"],
    hazards: ["Unexpected startup", "Stored pressure or gravity release", "Multiple energy sources", "Unverified isolation", "Workers reaching into danger zones"],
    requiredDocuments: ["Lockout procedure or isolation plan", "Verification record where used", "Equipment inspection or maintenance notes", "Toolbox talk attendance record"],
    wikiSlugs: ["electrical-safety-near-power-lines", "mobile-equipment", "incident-investigation"],
    toolboxTalkIds: ["lockout-before-maintenance", "stored-energy-hazards", "power-tool-guards"],
    checklistIds: ["power-tools", "mobile-equipment", "daily-site-inspection"],
    quizIds: ["lockout-tagout-quiz", "electrical-safety-quiz", "tool-and-equipment-safety-quiz"],
    formIds: ["equipment-inspection", "hazard-report", "incident-report"],
    printableSections: ["Identify every energy source before touching the equipment.", "Apply isolation and verify zero energy before maintenance or clearing starts.", "Keep body parts out of pinch, crush, and release paths.", "Record the isolation method and unresolved defects."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC lockout and equipment-specific procedure requirements before field use.",
  },
  {
    id: "whmis-chemical-storage",
    title: "WHMIS and chemical storage",
    scenario: "Receiving, storing, mixing, transferring, or using controlled products, fuels, adhesives, solvents, cleaners, or sealants on site.",
    demoQuery: "chemical storage whmis labels",
    keywords: ["whmis", "sds", "chemical", "solvent", "adhesive", "fuel", "label", "storage", "spill", "flammable"],
    hazards: ["Missing label or SDS access", "Incompatible storage", "Fire or spill exposure", "Skin, eye, or inhalation contact", "Improper disposal or transfer containers"],
    requiredDocuments: ["SDS access confirmation", "WHMIS label check", "Spill or hazard report where needed", "Storage inspection notes"],
    wikiSlugs: ["whmis-basics", "site-emergency-response-plan", "occupational-first-aid-requirements"],
    toolboxTalkIds: ["whmis-labels-and-sds-access", "chemical-storage-on-site", "eye-and-face-protection"],
    checklistIds: ["whmis-sds", "ppe", "emergency-response"],
    quizIds: ["whmis-sds-quiz", "ppe-quiz", "emergency-response-quiz"],
    formIds: ["hazard-report", "site-safety-inspection", "near-miss-report"],
    printableSections: ["Confirm labels and SDS access before product use.", "Separate incompatible products and control ignition sources.", "Match PPE and ventilation to the product hazard.", "Record spills, missing labels, or storage concerns."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC WHMIS, SDS, and product-specific requirements before field use.",
  },
  {
    id: "eye-face-protection-grinding",
    title: "Eye and face protection for grinding",
    scenario: "Grinding, chipping, cutting, drilling overhead, mixing chemicals, or using tools that throw particles, splash, dust, sparks, or heat.",
    demoQuery: "grinding sparks eye protection",
    keywords: ["eye protection", "face shield", "grinding", "sparks", "flying particles", "goggles", "overhead drilling", "splash", "ppe"],
    hazards: ["Flying particles", "Grinding sparks", "Chemical splash", "Dust in eyes", "Wrong protection for the hazard"],
    requiredDocuments: ["PPE selection check", "Toolbox talk attendance record", "Hazard report if protection is missing", "Equipment inspection where tool condition is involved"],
    wikiSlugs: ["whmis-basics", "silica-exposure-control", "site-orientation"],
    toolboxTalkIds: ["eye-and-face-protection", "power-tool-guards", "wet-cutting-and-hepa-cleanup"],
    checklistIds: ["ppe", "power-tools", "silica-dust"],
    quizIds: ["ppe-quiz", "tool-and-equipment-safety-quiz"],
    formIds: ["hazard-report", "equipment-inspection", "toolbox-talk-attendance"],
    printableSections: ["Identify the direction, source, and type of eye/face hazard.", "Choose glasses, goggles, face shield, or combined protection suited to the task.", "Stop work if nearby workers are exposed to sparks, dust, or particles.", "Record PPE gaps and corrections."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC PPE and manufacturer instruction requirements before field use.",
  },
  {
    id: "hearing-protection-noise",
    title: "Hearing protection and noise",
    scenario: "Workers are exposed to loud tools, impact work, compressors, generators, concrete cutting, grinding, or enclosed noisy work areas.",
    demoQuery: "concrete cutting noise hearing protection",
    keywords: ["hearing", "noise", "loud", "compressor", "generator", "cutting", "grinding", "impact", "ear plugs", "ear muffs"],
    hazards: ["High noise exposure", "Wrong or inconsistent hearing protection", "Communication failure", "Noise affecting adjacent workers", "Noisy enclosed work areas"],
    requiredDocuments: ["Noise hazard notes where required", "PPE selection check", "Toolbox talk attendance record", "Deficiency report for uncontrolled noise"],
    wikiSlugs: ["silica-exposure-control", "site-orientation", "occupational-first-aid-requirements"],
    toolboxTalkIds: ["hearing-protection", "silica-dust-controls", "power-tool-guards"],
    checklistIds: ["ppe", "power-tools", "daily-site-inspection"],
    quizIds: ["ppe-quiz", "tool-and-equipment-safety-quiz"],
    formIds: ["hazard-report", "site-safety-inspection", "toolbox-talk-attendance"],
    printableSections: ["Identify loud tasks and affected nearby workers before work starts.", "Choose hearing protection and communication methods suited to the task.", "Move or isolate work where possible and maintain emergency communication.", "Record uncontrolled noise concerns and follow-up."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC noise and PPE requirements before field use.",
  },
  {
    id: "heat-stress-response",
    title: "Heat stress response",
    scenario: "Outdoor or hot indoor work during high temperatures, heavy PPE use, roofing, concrete work, traffic control, or enclosed mechanical spaces.",
    demoQuery: "heat stress early signs",
    keywords: ["heat stress", "hot weather", "heat", "roofing", "dehydration", "shade", "water", "heavy ppe", "summer"],
    hazards: ["Heat exhaustion or heat stroke", "Dehydration", "Heavy PPE limiting cooling", "New workers not acclimatized", "Delayed recognition of symptoms"],
    requiredDocuments: ["Heat stress plan or task briefing where used", "Emergency response contact check", "Toolbox talk attendance record", "Incident or first aid report if symptoms occur"],
    wikiSlugs: ["occupational-first-aid-requirements", "site-emergency-response-plan", "site-orientation"],
    toolboxTalkIds: ["heat-stress-early-signs", "first-aid-access-and-reporting", "emergency-muster-and-headcount"],
    checklistIds: ["emergency-response", "first-aid-kit-first-aid-room", "daily-site-inspection"],
    quizIds: ["heat-cold-stress-quiz", "first-aid-quiz"],
    formIds: ["incident-report", "near-miss-report", "toolbox-talk-attendance"],
    printableSections: ["Review heat signs, hydration, rest, shade, pace, and buddy checks.", "Watch new or returning workers closely during hot tasks.", "Start emergency response promptly for serious symptoms.", "Record first aid, task changes, and follow-up controls."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC heat stress and emergency response requirements before field use.",
  },
  {
    id: "cold-stress-wet-work",
    title: "Cold stress and wet work",
    scenario: "Cold, wet, windy, or winter work involving exterior tasks, slab work, traffic control, deliveries, or workers in soaked clothing.",
    demoQuery: "cold stress wet clothing",
    keywords: ["cold stress", "wet clothing", "hypothermia", "wind", "winter", "cold", "rain", "traffic control", "exterior work"],
    hazards: ["Hypothermia or cold stress", "Reduced dexterity and grip", "Wet clothing", "Slips from ice or water", "Delayed reporting of symptoms"],
    requiredDocuments: ["Cold weather briefing where used", "Emergency response and first aid check", "Housekeeping or access inspection notes", "Toolbox talk attendance record"],
    wikiSlugs: ["occupational-first-aid-requirements", "site-emergency-response-plan", "site-orientation"],
    toolboxTalkIds: ["cold-stress-and-wet-clothing", "first-aid-access-and-reporting", "housekeeping-and-access-routes"],
    checklistIds: ["emergency-response", "housekeeping", "daily-site-inspection"],
    quizIds: ["heat-cold-stress-quiz", "first-aid-quiz"],
    formIds: ["hazard-report", "near-miss-report", "toolbox-talk-attendance"],
    printableSections: ["Check weather, wet clothing, warm-up options, access routes, and first aid response.", "Watch for shivering, confusion, numbness, and reduced coordination.", "Control ice, water, and poor traction before work continues.", "Record cold-stress concerns and corrective actions."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC cold stress, first aid, and site-specific weather procedures before field use.",
  },
  {
    id: "violence-harassment-reporting",
    title: "Violence and harassment reporting",
    scenario: "A worker reports threatening behaviour, harassment, aggressive public interaction, conflict between trades, or a respectful-site concern.",
    demoQuery: "harassment reporting on site",
    keywords: ["violence", "harassment", "threat", "aggressive", "respectful", "bullying", "public", "reporting", "conflict"],
    hazards: ["Unreported threats", "Worker intimidation", "Escalating public interaction", "Retaliation fear", "Poor documentation"],
    requiredDocuments: ["Incident or concern report", "Supervisor follow-up notes", "Corrective action log where needed", "Worker support and privacy notes"],
    wikiSlugs: ["site-orientation", "incident-investigation", "occupational-first-aid-requirements"],
    toolboxTalkIds: ["violence-and-harassment-reporting", "respectful-site-communication", "supervisor-stop-work-expectations"],
    checklistIds: ["incident-follow-up", "daily-site-inspection"],
    quizIds: ["violence-harassment-quiz", "supervisor-duties-quiz"],
    formIds: ["incident-report", "investigation-witness-statement", "corrective-action-log"],
    printableSections: ["Create a clear and private reporting path for the worker.", "Document facts, witnesses, immediate controls, and follow-up without unnecessary personal details.", "Escalate serious threats and protect workers from further exposure.", "Record corrective actions and review whether site controls need changes."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC violence, harassment, privacy, and employer procedure requirements before field use.",
  },
  {
    id: "supervisor-stop-work",
    title: "Supervisor stop-work expectations",
    scenario: "A supervisor or lead hand needs to pause unsafe work, brief a crew, document controls, or restart after a serious hazard is corrected.",
    demoQuery: "supervisor stop work expectation",
    keywords: ["supervisor", "stop work", "lead hand", "unsafe work", "restart", "briefing", "authority", "corrective action"],
    hazards: ["Unsafe work continuing", "Unclear authority", "Restart before controls are ready", "Poor documentation", "Workers unsure who decides"],
    requiredDocuments: ["Hazard report or deficiency record", "Corrective action log", "Toolbox talk attendance record", "Supervisor follow-up notes"],
    wikiSlugs: ["site-orientation", "incident-investigation", "fall-protection"],
    toolboxTalkIds: ["supervisor-stop-work-expectations", "refusing-unsafe-work", "incident-and-near-miss-reporting"],
    checklistIds: ["incident-follow-up", "daily-site-inspection"],
    quizIds: ["supervisor-duties-quiz", "refusing-unsafe-work-quiz"],
    formIds: ["hazard-report", "corrective-action-log", "toolbox-talk-attendance"],
    printableSections: ["State the hazard, stop point, temporary control, and person responsible for correction.", "Do not restart until controls are in place and workers understand the change.", "Document the reason for stop-work and the restart decision.", "Follow up on repeated hazards by trade, area, or task."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC supervisor duties, refusal, and employer procedure requirements before field use.",
  },
  {
    id: "prime-contractor-coordination",
    title: "Prime contractor coordination",
    scenario: "Multiple employers or trades are working in the same area, with overlapping hazards, shared access, deliveries, or high-risk work.",
    demoQuery: "prime contractor coordination multiple trades",
    keywords: ["prime contractor", "coordination", "multiple trades", "overlap", "shared access", "handoff", "site coordination", "interface"],
    hazards: ["Trade overlap", "Unclear responsibility", "Conflicting controls", "Shared access blocked", "High-risk work affecting other employers"],
    requiredDocuments: ["Coordination notes", "High-risk work board update", "Trade briefing or toolbox talk record", "Corrective action log for unresolved interface hazards"],
    wikiSlugs: ["site-orientation", "incident-investigation", "traffic-control", "mobile-equipment"],
    toolboxTalkIds: ["prime-contractor-coordination", "supervisor-stop-work-expectations", "housekeeping-and-access-routes"],
    checklistIds: ["daily-site-inspection", "housekeeping", "traffic-control"],
    quizIds: ["prime-contractor-site-coordination-quiz", "supervisor-duties-quiz"],
    formIds: ["subcontractor-safety-onboarding", "corrective-action-log", "site-safety-inspection"],
    printableSections: ["Identify which employers and tasks affect the same area.", "Align access, sequencing, emergency routes, and high-risk controls before work starts.", "Record unresolved interface hazards and who owns each correction.", "Re-brief crews when sequence, access, or hazard controls change."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC prime contractor and coordination requirements before field use.",
  },
  {
    id: "incident-near-miss-follow-up",
    title: "Incident and near-miss follow-up",
    scenario: "A near miss, injury, equipment contact, fall hazard, dropped object, utility strike, or uncontrolled exposure needs reporting and corrective action.",
    demoQuery: "near miss report follow up",
    keywords: ["incident", "near miss", "investigation", "witness", "corrective action", "report", "dropped object", "injury", "follow up"],
    hazards: ["Facts lost before review", "No corrective action owner", "Repeat hazard not identified", "Witness notes missing", "Incident treated as paperwork only"],
    requiredDocuments: ["Incident or near-miss report", "Witness statement where needed", "Corrective action log", "Related checklist or inspection notes"],
    wikiSlugs: ["incident-investigation", "site-emergency-response-plan", "occupational-first-aid-requirements"],
    toolboxTalkIds: ["incident-and-near-miss-reporting", "supervisor-stop-work-expectations", "refusing-unsafe-work"],
    checklistIds: ["incident-follow-up", "daily-site-inspection"],
    quizIds: ["incident-reporting-quiz", "supervisor-duties-quiz"],
    formIds: ["incident-report", "near-miss-report", "investigation-witness-statement", "corrective-action-log"],
    printableSections: ["Capture who, what, where, when, immediate controls, and witnesses while facts are fresh.", "Assign corrective action owners and due dates.", "Link the event to related hazards, talks, checklists, and wiki source notes.", "Review whether the same hazard exists elsewhere on site."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC incident reporting, investigation, and employer procedure requirements before field use.",
  },
  {
    id: "housekeeping-access-routes",
    title: "Housekeeping and access routes",
    scenario: "Material, cords, debris, waste, pallets, hoses, or stored equipment block access routes, emergency routes, stairs, corridors, or work faces.",
    demoQuery: "housekeeping access route blocked",
    keywords: ["housekeeping", "access route", "blocked", "debris", "cords", "waste", "stairs", "corridor", "emergency route", "egress"],
    hazards: ["Trips and slips", "Blocked emergency access", "Hidden openings or edges", "Material collapse or struck-by exposure", "Delayed first aid or evacuation"],
    requiredDocuments: ["Daily site inspection notes", "Deficiency or hazard report", "Corrective action log where repeated", "Toolbox talk attendance record"],
    wikiSlugs: ["site-orientation", "site-emergency-response-plan", "fall-protection", "traffic-control"],
    toolboxTalkIds: ["housekeeping-and-access-routes", "extension-cords-and-temporary-power", "emergency-muster-and-headcount"],
    checklistIds: ["housekeeping", "daily-site-inspection", "emergency-response"],
    quizIds: ["site-orientation-quiz", "emergency-response-quiz"],
    formIds: ["hazard-report", "corrective-action-log", "site-safety-inspection"],
    printableSections: ["Walk access, egress, stairs, emergency routes, and active work faces.", "Remove or control cords, debris, storage, hoses, and waste before work continues.", "Identify repeated trade or area patterns.", "Record owner, due date, and closeout evidence for unresolved access hazards."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC access, egress, housekeeping, and emergency route requirements before field use.",
  },
  {
    id: "first-aid-room-kit-readiness",
    title: "First aid kit / first aid room readiness",
    scenario: "A supervisor needs to verify first aid supplies, first aid room access, attendants, AED location, emergency contact details, or rescue access.",
    demoQuery: "first aid room kit check",
    keywords: ["first aid kit", "first aid room", "attendant", "aed", "supplies", "emergency contact", "ambulance access", "first aid"],
    hazards: ["First aid supplies missing", "Attendant or room not found", "AED not accessible", "Emergency access blocked", "Workers do not know reporting path"],
    requiredDocuments: ["First aid assessment or site first aid procedure", "First aid kit / room checklist", "Emergency response plan", "Incident report if first aid is provided"],
    wikiSlugs: ["occupational-first-aid-requirements", "cardiac-arrest-on-site", "site-emergency-response-plan"],
    toolboxTalkIds: ["first-aid-access-and-reporting", "aed-location-and-emergency-access", "cardiac-arrest-response-basics"],
    checklistIds: ["first-aid-kit-first-aid-room", "emergency-response"],
    quizIds: ["first-aid-quiz", "emergency-response-quiz"],
    formIds: ["incident-report", "site-safety-inspection", "toolbox-talk-attendance"],
    printableSections: ["Show workers the first aid location, attendant contact, AED, and access route.", "Check supplies, signage, emergency contact details, and communication method.", "Keep ambulance access and first aid room access clear.", "Record shortages, corrections, and first aid events as required by procedure."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC occupational first aid requirements and site-specific first aid assessment before field use.",
  },
  {
    id: "suspended-load-exclusion-zone",
    title: "Suspended load exclusion zone",
    scenario: "Workers, spotters, or delivery crews are near a crane, hoist, forklift, or rigged load path with suspended or elevated materials.",
    demoQuery: "suspended load exclusion zone",
    keywords: ["suspended load", "exclusion zone", "load path", "crane", "hoist", "forklift", "rigging", "dropped load", "struck by"],
    hazards: ["Workers under suspended loads", "Dropped or shifting load", "Unclear exclusion zone", "Poor signal communication", "Pedestrian path crosses lift area"],
    requiredDocuments: ["Lift or load movement briefing", "Exclusion zone layout", "Rigging inspection notes where relevant", "Toolbox talk attendance record"],
    wikiSlugs: ["cranes-and-hoists", "rigging-basics", "mobile-equipment", "traffic-control"],
    toolboxTalkIds: ["exclusion-zones-under-suspended-loads", "crane-pick-communication", "rigging-inspection-basics"],
    checklistIds: ["mobile-equipment", "traffic-control", "daily-site-inspection"],
    quizIds: ["cranes-rigging-quiz", "mobile-equipment-quiz"],
    formIds: ["hazard-report", "equipment-inspection", "toolbox-talk-attendance"],
    printableSections: ["Identify the full load path, landing area, swing radius, and pedestrian conflicts.", "Set and communicate the exclusion zone before the load moves.", "Stop movement if workers enter the zone or communication is unclear.", "Record lift-area deficiencies and corrective action owners."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC crane, hoist, mobile equipment, and rigging requirements before field use.",
  },
  {
    id: "pedestrian-detour-public-protection",
    title: "Pedestrian detour / public protection",
    scenario: "Construction work affects sidewalks, public paths, delivery gates, hoarding, traffic control, or pedestrian detours near a site boundary.",
    demoQuery: "pedestrian detour public protection",
    keywords: ["pedestrian", "detour", "public protection", "sidewalk", "hoarding", "traffic control", "delivery gate", "signage", "public"],
    hazards: ["Public entering work area", "Detour signage moved", "Delivery gate conflict", "Poor visibility", "Materials or equipment encroach on pedestrian route"],
    requiredDocuments: ["Traffic control or pedestrian detour plan", "Daily public-interface inspection notes", "Hazard report for route changes", "Toolbox talk attendance record"],
    wikiSlugs: ["traffic-control", "mobile-equipment", "site-emergency-response-plan"],
    toolboxTalkIds: ["pedestrian-detours", "traffic-control-around-deliveries", "spotter-communication"],
    checklistIds: ["traffic-control", "mobile-equipment", "daily-site-inspection"],
    quizIds: ["traffic-control-quiz", "mobile-equipment-quiz"],
    formIds: ["hazard-report", "site-safety-inspection", "corrective-action-log"],
    printableSections: ["Walk the public route before deliveries, noisy work, or hoarding changes.", "Confirm signage, barriers, spotters, lighting, and emergency access.", "Pause deliveries if pedestrian separation cannot be maintained.", "Record shifted signs, blocked routes, and corrective actions."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC traffic control, municipal permit, public protection, and site-specific requirements before field use.",
  },
  {
    id: "respirator-fit-seal-check",
    title: "Respirator fit and seal check",
    scenario: "A task requires respirator use for dust, silica, fumes, chemicals, or other airborne hazards, and workers need pre-task verification.",
    demoQuery: "respirator seal check silica",
    keywords: ["respirator", "seal check", "fit test", "silica", "dust", "fumes", "mask", "cartridge", "n95", "half mask"],
    hazards: ["Poor face seal", "Wrong filter or cartridge", "Facial hair affecting seal", "No fit verification", "Respirator used as substitute for source control"],
    requiredDocuments: ["Respirator and PPE verification where required", "Exposure control or task procedure", "Toolbox talk attendance record", "Hazard report if controls are missing"],
    wikiSlugs: ["respirators", "silica-exposure-control", "whmis-basics"],
    toolboxTalkIds: ["respirator-fit-and-seal-checks", "silica-dust-controls", "whmis-labels-and-sds-access"],
    checklistIds: ["ppe", "silica-dust", "whmis-sds"],
    quizIds: ["ppe-quiz", "silica-and-dust-quiz", "whmis-sds-quiz"],
    formIds: ["hazard-report", "training-matrix", "toolbox-talk-attendance"],
    printableSections: ["Confirm the airborne hazard, source controls, respirator type, filter/cartridge, and worker readiness.", "Perform required user seal checks before entering the exposure area.", "Stop work if fit, filter, storage, facial hair, or source controls are not acceptable.", "Record gaps and follow-up training or equipment actions."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC respirator, fit testing, exposure control, and site-specific procedure requirements before field use.",
  },
  {
    id: "roofing-edge-work",
    title: "Roofing edge work",
    scenario: "Workers perform roofing, membrane, flashing, parapet, material loading, or inspection tasks near roof edges, openings, or leading edges.",
    demoQuery: "roofing edge fall protection",
    keywords: ["roofing", "roof edge", "parapet", "membrane", "flashing", "leading edge", "fall protection", "anchor", "rescue"],
    hazards: ["Roof edge fall exposure", "Openings or skylight exposure", "Material handling near edge", "Unverified anchors", "No rescue plan"],
    requiredDocuments: ["Fall protection plan where required", "Rescue plan for fall arrest use", "Anchor and equipment inspection notes", "Toolbox talk attendance record"],
    wikiSlugs: ["fall-protection", "fall-protection-plan", "fall-arrest", "fall-restraint", "anchor-points", "fall-rescue-plan"],
    toolboxTalkIds: ["tie-off-planning-before-edge-work", "fall-rescue-readiness", "harness-inspection"],
    checklistIds: ["fall-protection", "ppe", "daily-site-inspection"],
    quizIds: ["fall-protection-quiz", "ppe-quiz"],
    formIds: ["hazard-report", "site-safety-inspection", "toolbox-talk-attendance"],
    printableSections: ["Identify roof edges, openings, skylights, material landing areas, and rescue access.", "Confirm guardrails, restraint, fall arrest, anchors, and travel limits before work starts.", "Pause work if weather, surface condition, or material handling changes exposure.", "Record equipment checks and unresolved roof-edge hazards."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC fall protection and site-specific roof work requirements before field use.",
  },
  {
    id: "formwork-leading-edge",
    title: "Formwork and leading edge",
    scenario: "Forming, stripping, deck layout, guardrail changes, slab edge work, or material staging creates fall or struck-by exposure.",
    demoQuery: "formwork leading edge guardrail",
    keywords: ["formwork", "leading edge", "deck", "slab", "stripping", "guardrail", "opening", "fall protection", "material staging"],
    hazards: ["Leading edge fall exposure", "Openings hidden by material", "Guardrails removed for work sequence", "Material falling or shifting", "Unclear handoff between trades"],
    requiredDocuments: ["Fall protection plan where required", "Guardrail or opening-cover inspection notes", "Trade coordination notes", "Toolbox talk attendance record"],
    wikiSlugs: ["fall-protection", "guardrails", "fall-protection-plan", "anchor-points", "site-orientation"],
    toolboxTalkIds: ["guardrails-and-floor-openings", "tie-off-planning-before-edge-work", "prime-contractor-coordination"],
    checklistIds: ["fall-protection", "daily-site-inspection", "housekeeping"],
    quizIds: ["fall-protection-quiz", "prime-contractor-site-coordination-quiz"],
    formIds: ["hazard-report", "site-safety-inspection", "corrective-action-log"],
    printableSections: ["Walk slab edges, openings, guardrail changes, and material staging before work starts.", "Confirm who owns temporary controls during forming, stripping, and handoff.", "Keep covers visible and secured, and stop work if controls are removed without replacement.", "Record guardrail/opening deficiencies and trade coordination actions."],
    reviewNotice: "Draft safety pack only. Verify current WorkSafeBC fall protection, construction, formwork, and site-specific procedure requirements before field use.",
  },
];

export const safetyPacks = [...coreSafetyPacks, ...supplementalSafetyPacks];

const stopWords = new Set([
  "a",
  "an",
  "and",
  "are",
  "at",
  "for",
  "in",
  "near",
  "of",
  "on",
  "or",
  "the",
  "to",
  "with",
]);

export function getSafetyPackById(id) {
  return safetyPacks.find((pack) => pack.id === id) || null;
}

export function searchSafetyPacks(query) {
  const normalizedQuery = normalizeSearchText(query);
  const queryTerms = tokenize(query);
  const ranked = safetyPacks.map((pack) => {
    const searchable = normalizeSearchText(
      [
        pack.title,
        pack.scenario,
        pack.demoQuery,
        ...pack.keywords,
        ...pack.hazards,
        ...pack.requiredDocuments,
      ].join(" "),
    );

    const phraseMatches = pack.keywords.filter((keyword) => {
      const normalizedKeyword = normalizeSearchText(keyword);
      return normalizedQuery && normalizedQuery.includes(normalizedKeyword);
    });
    const termMatches = queryTerms.filter((term) => searchable.includes(term));
    const matchedTerms = unique([...phraseMatches, ...termMatches]).slice(0, 8);
    const score = phraseMatches.length * 5 + termMatches.length * 2;

    return {
      ...pack,
      matchedTerms,
      score,
    };
  });

  const matches = ranked.filter((pack) => pack.score > 0);
  return (matches.length ? matches : ranked).sort((a, b) => b.score - a.score || a.title.localeCompare(b.title));
}

function tokenize(value) {
  return normalizeSearchText(value)
    .split(" ")
    .filter((term) => term.length > 2 && !stopWords.has(term));
}

function normalizeSearchText(value) {
  return String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function unique(items) {
  return [...new Set(items.filter(Boolean))];
}
