export const SUBMITTED_FORM_TRANSLATION_LANGUAGES = [
  { code: "es", label: "Spanish" },
  { code: "fr", label: "French" },
  { code: "hi", label: "Hindi" },
];

const RAW_PHRASEBOOKS = {
  es: {
    "Submitted Form": "Formulario enviado",
    "New Worker Orientation": "Orientacion de trabajador nuevo",
    "Toolbox Talk": "Charla de seguridad",
    "Toolbox Talk Copy 2": "Copia 2 de charla de seguridad",
    "Site Inspection": "Inspeccion del sitio",
    "Staff Sign-Off": "Aprobacion del personal",
    "Not signed": "Sin firmar",
    "No staff sign-off recorded yet.": "Aun no hay aprobacion del personal registrada.",
    "Signed": "Firmado",
    "Comments": "Comentarios",
    "Submitted": "Enviado",
    "Phone": "Telefono",
    "Username": "Usuario",
    "Mode": "Modo",
    "Backup": "Respaldo",
    "Backup error": "Error de respaldo",
    "Open backup": "Abrir respaldo",
    "Notes": "Notas",
    "Fill Form": "Llenar formulario",
    "Submit File": "Enviar archivo",
    "Backed up": "Respaldado",
    "Pending": "Pendiente",
    "Failed": "Fallido",
    "Unknown": "Desconocido",
    "Reviewed": "Revisado",
    "Pending review": "Pendiente de revision",
    "Linked Action Items": "Acciones vinculadas",
    "Action item": "Accion",
    "Unassigned": "Sin asignar",
    "Files": "Archivos",
    "Opening...": "Abriendo...",
    "Opening": "Abriendo",
    "Open": "Abrir",
    "Attachment": "Adjunto",
    "Preview": "Vista previa",
    "Submitted file package": "Paquete de archivos enviado",
    "No files uploaded": "No se subieron archivos",
    "uploaded file": "archivo subido",
    "uploaded files": "archivos subidos",
    "was submitted as an uploaded attachment package.": "se envio como un paquete de adjuntos subidos.",
    "File package summary": "Resumen del paquete de archivos",
    "total": "total",
    "Image": "Imagen",
    "Document": "Documento",
    "Spreadsheet": "Hoja de calculo",
    "PDF": "PDF",
    "File": "Archivo",
    "Backup:": "Respaldo:",

    "Meeting Info": "Informacion de la reunion",
    "Project": "Proyecto",
    "Address": "Direccion",
    "Date": "Fecha",
    "Time": "Hora",
    "Presenter": "Presentador",
    "Supervisor": "Supervisor",
    "Topics": "Temas",
    "Topics Discussed": "Temas discutidos",
    "Review Notes": "Notas de revision",
    "Safety Concerns": "Preocupaciones de seguridad",
    "Attendance": "Asistencia",
    "Final Check": "Verificacion final",
    "Confirmed by": "Confirmado por",
    "Confirmation date": "Fecha de confirmacion",
    "Participation confirmed": "Participacion confirmada",
    "Yes": "Si",
    "No": "No",
    "attendee": "asistente",
    "attendees": "asistentes",
    "Identification": "Identificacion",
    "General Safety": "Seguridad general",
    "PPE": "EPP",
    "Fall Protection": "Proteccion contra caidas",
    "Equipment": "Equipo",
    "First Aid": "Primeros auxilios",

    "Inspection Info": "Informacion de inspeccion",
    "Area": "Area",
    "Inspector": "Inspector",
    "Trades": "Oficios",
    "Reviewer": "Revisor",
    "Observations": "Observaciones",
    "Positive": "Positivo",
    "High-risk work": "Trabajo de alto riesgo",
    "Immediate controls": "Controles inmediatos",
    "Follow-up": "Seguimiento",
    "Deficiencies": "Deficiencias",
    "No deficiencies found during this inspection.": "No se encontraron deficiencias durante esta inspeccion.",
    "No deficiencies recorded.": "No se registraron deficiencias.",
    "Deficiency": "Deficiencia",
    "Category": "Categoria",
    "Location": "Ubicacion",
    "Immediate control": "Control inmediato",
    "Corrective action": "Accion correctiva",
    "Assignee": "Responsable",
    "Due": "Vence",

    "NEW WORKER ORIENTATION": "ORIENTACION DE TRABAJADOR NUEVO",
    "ORIENTATION #": "ORIENTACION #",
    "Orientation #": "Orientacion #",
    "Worker Name": "Nombre del trabajador",
    "WORKER NAME": "NOMBRE DEL TRABAJADOR",
    "Telephone Number": "Numero de telefono",
    "TELEPHONE NUMBER": "NUMERO DE TELEFONO",
    "Company and Sub-Trade": "Empresa y suboficio",
    "COMPANY AND SUB-TRADE": "EMPRESA Y SUBOFICIO",
    "Occupation": "Ocupacion",
    "OCCUPATION": "OCUPACION",
    "Supervisor Name": "Nombre del supervisor",
    "SUPERVISOR NAME": "NOMBRE DEL SUPERVISOR",
    "Supervisor Telephone": "Telefono del supervisor",
    "SUPERVISOR TELEPHONE": "TELEFONO DEL SUPERVISOR",
    "Emergency Contact Information": "Informacion de contacto de emergencia",
    "Emergency Contact Name": "Nombre del contacto de emergencia",
    "Relationship": "Relacion",
    "Paper Orientation Images": "Imagenes de orientacion en papel",
    "Muster Station": "Punto de reunion",
    "Before and during your work on our site you must meet, and comply with, all company and WorkSafeBC requirements. Review and initial each section below. Ensure you understand and follow all company rules and OHS Regulations. The items with an * will have continual competency observations.":
      "Antes y durante su trabajo en nuestro sitio debe cumplir con todos los requisitos de la empresa y WorkSafeBC. Revise e iniciale cada seccion abajo. Asegurese de entender y seguir todas las reglas de la empresa y las normas de OHS. Los puntos con * tendran observaciones continuas de competencia.",
    "1 - SITE SAFETY AND EMERGENCY PROCEDURES": "1 - SEGURIDAD DEL SITIO Y PROCEDIMIENTOS DE EMERGENCIA",
    "2 - POTENTIAL HAZARDS AND RESPONSIBILITIES": "2 - PELIGROS POTENCIALES Y RESPONSABILIDADES",
    "3 - PERSONAL PROTECTIVE EQUIPMENT": "3 - EQUIPO DE PROTECCION PERSONAL",
    "4 - WORKPLACE SAFETY RULES AND INFORMATION": "4 - REGLAS E INFORMACION DE SEGURIDAD EN EL LUGAR DE TRABAJO",
    "5 - TRAFFIC CONTROL": "5 - CONTROL DE TRAFICO",
    "TRAFFIC CONTROL": "CONTROL DE TRAFICO",
    "6 - RIGHTS AND RESPONSIBILITIES": "6 - DERECHOS Y RESPONSABILIDADES",
    "7 - TRAINING AND CERTIFICATIONS": "7 - CAPACITACION Y CERTIFICACIONES",
    "8 - MEDICAL INFORMATION (Optional) - kept confidential and only provided to EMS if needed":
      "8 - INFORMACION MEDICA (Opcional) - confidencial y solo proporcionada a EMS si es necesario",
    "Trade Orientation Confirmation": "Confirmacion de orientacion de oficio",
    "9 - WORKER ACKNOWLEDGMENT": "9 - RECONOCIMIENTO DEL TRABAJADOR",
    "Appia's Health and Safety policy": "Politica de salud y seguridad de Appia",
    "Location of First Aid facilities and our FA attendants": "Ubicacion de las instalaciones de primeros auxilios y nuestros asistentes de primeros auxilios",
    "How to report illness and injury without delay": "Como reportar enfermedad y lesion sin demora",
    "Emergency procedures & muster station": "Procedimientos de emergencia y punto de reunion",
    "Air horns and Fire extinguishers (Located on every level)": "Bocinas de aire y extintores (ubicados en cada nivel)",
    "Access and egress route clear of obstructions and hazards": "Rutas de acceso y salida libres de obstrucciones y peligros",
    "Duty to report hazards, incidents, near misses & unsafe acts": "Deber de reportar peligros, incidentes, casi accidentes y actos inseguros",
    "Accident/Incident investigations and reporting procedures": "Investigaciones de accidentes/incidentes y procedimientos de reporte",
    "Housekeeping: ensure work area is clean at end of day": "Orden y limpieza: asegure que el area de trabajo quede limpia al final del dia",
    "Working alone or in isolation": "Trabajo solo o en aislamiento",
    "Bullying, harassment, threats, and violence- how to report": "Intimidacion, acoso, amenazas y violencia: como reportar",
    "Theft and vandalism": "Robo y vandalismo",
    "Alcohol, drugs & impairment": "Alcohol, drogas y deterioro",
    "Stress, Excessive workload, mentally fit for work": "Estres, carga excesiva y aptitud mental para trabajar",
    "SDS location, purpose, and key info on SDS and spill clean up": "Ubicacion de SDS, proposito e informacion clave sobre SDS y limpieza de derrames",
    "*Crane operations around site": "*Operaciones de grua alrededor del sitio",
    "Operating equipment with overlapping work zones": "Operacion de equipo con zonas de trabajo superpuestas",
    "*Loading / Unloading Vehicles / Cranes / Rigging": "*Carga / descarga de vehiculos / gruas / aparejos",
    "*Working at heights": "*Trabajo en alturas",
    "*Fall protection systems - guardrails, restraint, arrest, other": "*Sistemas de proteccion contra caidas: barandas, restriccion, detencion, otros",
    "*Leading edge work (permit required)": "*Trabajo en borde expuesto (permiso requerido)",
    "*Dropped object prevention program": "*Programa de prevencion de objetos caidos",
    "*Ladder use / work platforms": "*Uso de escaleras / plataformas de trabajo",
    "Access / Egress": "Acceso / salida",
    "*Exposure to Silica Dust (ECP required)": "*Exposicion a polvo de silice (ECP requerido)",
    "*Hot Work (permit required)": "*Trabajo en caliente (permiso requerido)",
    "*Confined Spaces (permit required)": "*Espacios confinados (permiso requerido)",
    "Electrical Safety / Proximity to Powerlines": "Seguridad electrica / proximidad a lineas electricas",
    "*Operating MEWPs (Scissor lift, etc.) & mobile equipment": "*Operacion de MEWP (elevador de tijera, etc.) y equipo movil",
    "Working around mobile equipment": "Trabajo alrededor de equipo movil",
    "Lifting Materials by Hand (MSI prevention)": "Levantamiento manual de materiales (prevencion MSI)",
    "Rebar Protection and protruding objects": "Proteccion de varillas y objetos salientes",
    "Floor Openings": "Aberturas en pisos",
    "Scaffolding/Swing stage - Work in high-risk situations": "Andamios/plataformas colgantes - trabajo en situaciones de alto riesgo",
    "Concrete Formwork / Placing Concrete / Fly Tables": "Encofrado de concreto / colocacion de concreto / mesas volantes",
    "Defective tools and equipment": "Herramientas y equipos defectuosos",
    "Excavations, Trenches, and underground services": "Excavaciones, zanjas y servicios subterraneos",
    "Hierarchy of hazard controls": "Jerarquia de controles de peligros",
    "Acceptable standards: CSA & ANSI": "Normas aceptables: CSA y ANSI",
    "Required PPE: Hard hat, safety boots & hi-visibility clothing": "EPP requerido: casco, botas de seguridad y ropa de alta visibilidad",
    "Required Clothing: Long pants and shirt with sleeves": "Ropa requerida: pantalones largos y camisa con mangas",
    "PPE fitting, Inspection & replacement": "Ajuste, inspeccion y reemplazo de EPP",
    "Specialized PPE is provided by your employer": "El EPP especializado es proporcionado por su empleador",
    "Follow manufacturer's instructions, SWP and SJP": "Siga las instrucciones del fabricante, SWP y SJP",
    "Hearing Conservation Program": "Programa de conservacion auditiva",
    "Respiratory Protection Program": "Programa de proteccion respiratoria",
    "Site rules (and where to find them)": "Reglas del sitio (y donde encontrarlas)",
    "Disciplinary policy": "Politica disciplinaria",
    "Reviewing safe job procedures and safe work practices": "Revision de procedimientos y practicas de trabajo seguros",
    "Public interactions and radio etiquette": "Interacciones publicas y etiqueta de radio",
    "Worker Health and Safety Representative(s) and JOHS Committee": "Representante(s) de salud y seguridad de trabajadores y comite JOHS",
    "Toolbox/safety meeting and safety committees": "Reunion de caja de herramientas/seguridad y comites de seguridad",
    "Compliance with OHS Program, basics of what is in it": "Cumplimiento del programa OHS y conceptos basicos de su contenido",
    "Location of WSBC regulations, OHS Program": "Ubicacion de regulaciones WSBC y programa OHS",
    "Traffic (city and WSBC) and Noise Bylaw": "Trafico (ciudad y WSBC) y reglamento de ruido",
    "Daily Hazard Assessment is completed prior to work": "La evaluacion diaria de peligros se completa antes del trabajo",
    "Safe standing location & escape route identified/reviewed": "Ubicacion segura y ruta de escape identificadas/revisadas",
    "TCP's with appropriate PPE for the task": "TCP con EPP adecuado para la tarea",
    "WORKER RIGHT TO:": "DERECHO DEL TRABAJADOR A:",
    "REFUSE unsafe work (that could affect the health and safety of you and others)": "RECHAZAR trabajo inseguro (que pueda afectar su salud y seguridad o la de otros)",
    "KNOW workplace hazards and controls (as discussed in this orientation and while on the job)": "CONOCER los peligros y controles del lugar de trabajo (como se trato en esta orientacion y durante el trabajo)",
    "PARTICIPATE in health and safety activities (ex. Reporting unsafe acts or participating in the JOHS committee)": "PARTICIPAR en actividades de salud y seguridad (por ejemplo, reportar actos inseguros o participar en el comite JOHS)",
    "BE SUPERVISED by a competent supervisor": "SER SUPERVISADO por un supervisor competente",
    "YOU ARE RESPONSIBLE TO:": "USTED ES RESPONSABLE DE:",
    "Work safely and follow the Site Safety Rules": "Trabajar de forma segura y seguir las reglas de seguridad del sitio",
    "Participate in, follow, and sign the Daily Hazard Assessment (FLRA/DHA/PSHA) as directed by your Supervisor": "Participar, seguir y firmar la evaluacion diaria de peligros (FLRA/DHA/PSHA) segun indique su supervisor",
    "Use equipment you're competent and authorized to use, as per Manufacturer's Instructions": "Usar equipos para los que es competente y esta autorizado, segun las instrucciones del fabricante",
    "Report hazards - to your supervisor or site safety personnel without delay": "Reportar peligros a su supervisor o personal de seguridad del sitio sin demora",
    "Clean up your mess as soon as possible AND before end of every shift": "Limpiar su area lo antes posible y antes del final de cada turno",
    "Correct unsafe conditions and report all incidents and injuries - regardless of severity": "Corregir condiciones inseguras y reportar todos los incidentes y lesiones, sin importar la gravedad",
    "Control and correct any hazard you create without delay": "Controlar y corregir cualquier peligro que usted cree sin demora",
    "Provide proof of training BEFORE conducting work that requires training or certification": "Proporcionar prueba de capacitacion ANTES de realizar trabajo que requiere capacitacion o certificacion",
    "Respect the workplace by using the functioning washroom facilities": "Respetar el lugar de trabajo usando los banos disponibles",
    "Do you understand and agree to follow all company rules and OHS regulations regarding the topic reviewed in, Section 1: SITE SAFETY AND EMERGENCY PROCEDURES?":
      "Entiende y acepta seguir todas las reglas de la empresa y las normas de OHS sobre el tema revisado en la Seccion 1: SEGURIDAD DEL SITIO Y PROCEDIMIENTOS DE EMERGENCIA?",
    "Will you be doing traffic control on our site?": "Realizara control de trafico en nuestro sitio?",
    "Do you have the following training or certifications:": "Tiene la siguiente capacitacion o certificaciones:",
    "WHMIS training (required by regulation)": "Capacitacion WHMIS (requerida por regulacion)",
    "Respirator fit tests": "Pruebas de ajuste de respirador",
    "Annual hearing tests": "Pruebas auditivas anuales",
    "Fall protection training?": "Capacitacion en proteccion contra caidas?",
    "Confined space training?": "Capacitacion en espacios confinados?",
    "Mobile Equipment training?": "Capacitacion en equipo movil?",
    "UPLOAD OR TAKE PHOTOS OF CERTIFICATIONS HERE (including certifications not listed above IF required for your position)":
      "SUBA O TOME FOTOS DE CERTIFICACIONES AQUI (incluidas certificaciones no listadas arriba SI son requeridas para su puesto)",
    "Do you suffer / have you ever suffered from any form of heart or lung condition?":
      "Sufre o ha sufrido alguna condicion cardiaca o pulmonar?",
    "Do you have any allergies to food or drugs?": "Tiene alergias a alimentos o medicamentos?",
    "Do you suffer / have you ever suffered any chronic condition that could affect First Aid?":
      "Sufre o ha sufrido alguna condicion cronica que podria afectar los primeros auxilios?",
    "Are you currently being prescribed any medication (please list)?":
      "Actualmente le recetan algun medicamento (indique cual)?",
    "Are you less than 25 years old or less than one year of experience in construction?":
      "Tiene menos de 25 anos o menos de un ano de experiencia en construccion?",
    "Yes - stay after this orientation for additional info": "Si - quedarse despues de esta orientacion para informacion adicional",
    "Have you received a New or Young Worker Orientation or training by your Employer?":
      "Ha recibido orientacion o capacitacion de trabajador nuevo o joven por parte de su empleador?",
    "Date of orientation by employer": "Fecha de orientacion por el empleador",
    "I acknowledge that I will follow the above information. I understand my responsibilities for my health and safety on site. I also agree to participating in my Employer's Injury Management/Return to Work Program, and any other Health and Safety activities.":
      "Reconozco que seguire la informacion anterior. Entiendo mis responsabilidades para mi salud y seguridad en el sitio. Tambien acepto participar en el programa de manejo de lesiones/regreso al trabajo de mi empleador y en otras actividades de salud y seguridad.",
    "Worker's Name": "Nombre del trabajador",
    "Worker Signature": "Firma del trabajador",
    "ORIENTATOR TO COMPLETE: I have reviewed the above workers information and it is complete.":
      "PARA COMPLETAR POR EL ORIENTADOR: He revisado la informacion del trabajador anterior y esta completa.",
    "Orientator's provider": "Proveedor del orientador",
    "Orientator's Signature": "Firma del orientador",
  },
  fr: {
    "Submitted Form": "Formulaire soumis",
    "New Worker Orientation": "Orientation des nouveaux travailleurs",
    "Toolbox Talk": "Causerie de securite",
    "Toolbox Talk Copy 2": "Copie 2 de causerie de securite",
    "Site Inspection": "Inspection du site",
    "Staff Sign-Off": "Approbation du personnel",
    "Not signed": "Non signe",
    "No staff sign-off recorded yet.": "Aucune approbation du personnel n'est encore enregistree.",
    "Signed": "Signe",
    "Comments": "Commentaires",
    "Submitted": "Soumis",
    "Phone": "Telephone",
    "Username": "Nom d'utilisateur",
    "Mode": "Mode",
    "Backup": "Sauvegarde",
    "Backup error": "Erreur de sauvegarde",
    "Open backup": "Ouvrir la sauvegarde",
    "Notes": "Notes",
    "Fill Form": "Remplir le formulaire",
    "Submit File": "Soumettre un fichier",
    "Backed up": "Sauvegarde",
    "Pending": "En attente",
    "Failed": "Echec",
    "Unknown": "Inconnu",
    "Reviewed": "Revise",
    "Pending review": "En attente de revision",
    "Linked Action Items": "Actions liees",
    "Action item": "Action",
    "Unassigned": "Non assigne",
    "Files": "Fichiers",
    "Opening...": "Ouverture...",
    "Opening": "Ouverture",
    "Open": "Ouvrir",
    "Attachment": "Piece jointe",
    "Preview": "Apercu",
    "Submitted file package": "Paquet de fichiers soumis",
    "No files uploaded": "Aucun fichier televerse",
    "uploaded file": "fichier televerse",
    "uploaded files": "fichiers televerses",
    "was submitted as an uploaded attachment package.": "a ete soumis comme paquet de pieces jointes televersees.",
    "File package summary": "Resume du paquet de fichiers",
    "total": "total",
    "Image": "Image",
    "Document": "Document",
    "Spreadsheet": "Feuille de calcul",
    "PDF": "PDF",
    "File": "Fichier",
    "Backup:": "Sauvegarde :",

    "Meeting Info": "Information sur la reunion",
    "Project": "Projet",
    "Address": "Adresse",
    "Date": "Date",
    "Time": "Heure",
    "Presenter": "Presentateur",
    "Supervisor": "Superviseur",
    "Topics": "Sujets",
    "Topics Discussed": "Sujets discutes",
    "Review Notes": "Notes de revision",
    "Safety Concerns": "Preoccupations de securite",
    "Attendance": "Presence",
    "Final Check": "Verification finale",
    "Confirmed by": "Confirme par",
    "Confirmation date": "Date de confirmation",
    "Participation confirmed": "Participation confirmee",
    "Yes": "Oui",
    "No": "Non",
    "attendee": "participant",
    "attendees": "participants",
    "Identification": "Identification",
    "General Safety": "Securite generale",
    "PPE": "EPI",
    "Fall Protection": "Protection contre les chutes",
    "Equipment": "Equipement",
    "First Aid": "Premiers soins",

    "Inspection Info": "Information d'inspection",
    "Area": "Zone",
    "Inspector": "Inspecteur",
    "Trades": "Metiers",
    "Reviewer": "Reviseur",
    "Observations": "Observations",
    "Positive": "Positif",
    "High-risk work": "Travail a haut risque",
    "Immediate controls": "Mesures immediates",
    "Follow-up": "Suivi",
    "Deficiencies": "Deficiences",
    "No deficiencies found during this inspection.": "Aucune deficience trouvee pendant cette inspection.",
    "No deficiencies recorded.": "Aucune deficience enregistree.",
    "Deficiency": "Deficience",
    "Category": "Categorie",
    "Location": "Emplacement",
    "Immediate control": "Mesure immediate",
    "Corrective action": "Mesure corrective",
    "Assignee": "Responsable",
    "Due": "Echeance",

    "NEW WORKER ORIENTATION": "ORIENTATION DES NOUVEAUX TRAVAILLEURS",
    "ORIENTATION #": "ORIENTATION #",
    "Orientation #": "Orientation #",
    "Worker Name": "Nom du travailleur",
    "WORKER NAME": "NOM DU TRAVAILLEUR",
    "Telephone Number": "Numero de telephone",
    "TELEPHONE NUMBER": "NUMERO DE TELEPHONE",
    "Company and Sub-Trade": "Entreprise et sous-metier",
    "COMPANY AND SUB-TRADE": "ENTREPRISE ET SOUS-METIER",
    "Occupation": "Profession",
    "OCCUPATION": "PROFESSION",
    "Supervisor Name": "Nom du superviseur",
    "SUPERVISOR NAME": "NOM DU SUPERVISEUR",
    "Supervisor Telephone": "Telephone du superviseur",
    "SUPERVISOR TELEPHONE": "TELEPHONE DU SUPERVISEUR",
    "Emergency Contact Information": "Coordonnees d'urgence",
    "Emergency Contact Name": "Nom du contact d'urgence",
    "Relationship": "Relation",
    "Paper Orientation Images": "Images d'orientation papier",
    "Muster Station": "Point de rassemblement",
    "Before and during your work on our site you must meet, and comply with, all company and WorkSafeBC requirements. Review and initial each section below. Ensure you understand and follow all company rules and OHS Regulations. The items with an * will have continual competency observations.":
      "Avant et pendant votre travail sur notre site, vous devez respecter toutes les exigences de l'entreprise et de WorkSafeBC. Revisez et paraphez chaque section ci-dessous. Assurez-vous de comprendre et suivre toutes les regles de l'entreprise et les reglements OHS. Les elements avec * auront des observations continues de competence.",
    "1 - SITE SAFETY AND EMERGENCY PROCEDURES": "1 - SECURITE DU SITE ET PROCEDURES D'URGENCE",
    "2 - POTENTIAL HAZARDS AND RESPONSIBILITIES": "2 - DANGERS POTENTIELS ET RESPONSABILITES",
    "3 - PERSONAL PROTECTIVE EQUIPMENT": "3 - EQUIPEMENT DE PROTECTION INDIVIDUELLE",
    "4 - WORKPLACE SAFETY RULES AND INFORMATION": "4 - REGLES ET INFORMATIONS DE SECURITE AU TRAVAIL",
    "5 - TRAFFIC CONTROL": "5 - CONTROLE DE LA CIRCULATION",
    "TRAFFIC CONTROL": "CONTROLE DE LA CIRCULATION",
    "6 - RIGHTS AND RESPONSIBILITIES": "6 - DROITS ET RESPONSABILITES",
    "7 - TRAINING AND CERTIFICATIONS": "7 - FORMATION ET CERTIFICATIONS",
    "8 - MEDICAL INFORMATION (Optional) - kept confidential and only provided to EMS if needed":
      "8 - RENSEIGNEMENTS MEDICAUX (facultatif) - confidentiels et fournis aux EMS seulement si necessaire",
    "Trade Orientation Confirmation": "Confirmation d'orientation du metier",
    "9 - WORKER ACKNOWLEDGMENT": "9 - RECONNAISSANCE DU TRAVAILLEUR",
    "Appia's Health and Safety policy": "Politique de sante et securite d'Appia",
    "Location of First Aid facilities and our FA attendants": "Emplacement des installations de premiers soins et de nos secouristes",
    "How to report illness and injury without delay": "Comment signaler sans delai une maladie ou blessure",
    "Emergency procedures & muster station": "Procedures d'urgence et point de rassemblement",
    "Air horns and Fire extinguishers (Located on every level)": "Cornes de brume et extincteurs (situes a chaque niveau)",
    "Access and egress route clear of obstructions and hazards": "Voies d'acces et de sortie libres d'obstructions et de dangers",
    "Duty to report hazards, incidents, near misses & unsafe acts": "Obligation de signaler dangers, incidents, quasi-accidents et actes dangereux",
    "Accident/Incident investigations and reporting procedures": "Enquetes d'accident/incident et procedures de rapport",
    "Housekeeping: ensure work area is clean at end of day": "Tenue des lieux : s'assurer que la zone de travail est propre en fin de journee",
    "Working alone or in isolation": "Travail seul ou isole",
    "Bullying, harassment, threats, and violence- how to report": "Intimidation, harcelement, menaces et violence - comment signaler",
    "Theft and vandalism": "Vol et vandalisme",
    "Alcohol, drugs & impairment": "Alcool, drogues et facultes affaiblies",
    "Stress, Excessive workload, mentally fit for work": "Stress, charge excessive et aptitude mentale au travail",
    "SDS location, purpose, and key info on SDS and spill clean up": "Emplacement des SDS, but et renseignements cles sur les SDS et le nettoyage des deversements",
    "Acceptable standards: CSA & ANSI": "Normes acceptables : CSA et ANSI",
    "Required PPE: Hard hat, safety boots & hi-visibility clothing": "EPI requis : casque, bottes de securite et vetements haute visibilite",
    "Required Clothing: Long pants and shirt with sleeves": "Vetements requis : pantalons longs et chemise a manches",
    "PPE fitting, Inspection & replacement": "Ajustement, inspection et remplacement de l'EPI",
    "Specialized PPE is provided by your employer": "L'EPI specialise est fourni par votre employeur",
    "Follow manufacturer's instructions, SWP and SJP": "Suivre les instructions du fabricant, SWP et SJP",
    "Hearing Conservation Program": "Programme de conservation de l'ouie",
    "Respiratory Protection Program": "Programme de protection respiratoire",
    "Site rules (and where to find them)": "Regles du site (et ou les trouver)",
    "Disciplinary policy": "Politique disciplinaire",
    "Reviewing safe job procedures and safe work practices": "Reviser les procedures et pratiques de travail securitaires",
    "Public interactions and radio etiquette": "Interactions avec le public et etiquette radio",
    "Worker Health and Safety Representative(s) and JOHS Committee": "Representant(s) sante-securite des travailleurs et comite JOHS",
    "Toolbox/safety meeting and safety committees": "Reunion de securite et comites de securite",
    "Compliance with OHS Program, basics of what is in it": "Conformite au programme OHS et notions de base",
    "Location of WSBC regulations, OHS Program": "Emplacement des reglements WSBC et du programme OHS",
    "Traffic (city and WSBC) and Noise Bylaw": "Circulation (ville et WSBC) et reglement sur le bruit",
    "Daily Hazard Assessment is completed prior to work": "L'evaluation quotidienne des dangers est terminee avant le travail",
    "Safe standing location & escape route identified/reviewed": "Emplacement securitaire et voie d'evacuation identifies/revises",
    "TCP's with appropriate PPE for the task": "TCP avec EPI approprie pour la tache",
    "WORKER RIGHT TO:": "DROIT DU TRAVAILLEUR DE :",
    "REFUSE unsafe work (that could affect the health and safety of you and others)": "REFUSER un travail dangereux (qui pourrait toucher votre sante et securite ou celles des autres)",
    "KNOW workplace hazards and controls (as discussed in this orientation and while on the job)": "CONNAITRE les dangers et controles du lieu de travail (discutes dans cette orientation et au travail)",
    "PARTICIPATE in health and safety activities (ex. Reporting unsafe acts or participating in the JOHS committee)": "PARTICIPER aux activites de sante et securite (ex. signaler des actes dangereux ou participer au comite JOHS)",
    "BE SUPERVISED by a competent supervisor": "ETRE SUPERVISE par un superviseur competent",
    "YOU ARE RESPONSIBLE TO:": "VOUS ETES RESPONSABLE DE :",
    "Work safely and follow the Site Safety Rules": "Travailler securitairement et suivre les regles de securite du site",
    "Participate in, follow, and sign the Daily Hazard Assessment (FLRA/DHA/PSHA) as directed by your Supervisor": "Participer, suivre et signer l'evaluation quotidienne des dangers (FLRA/DHA/PSHA) selon les directives de votre superviseur",
    "Use equipment you're competent and authorized to use, as per Manufacturer's Instructions": "Utiliser l'equipement pour lequel vous etes competent et autorise, selon les instructions du fabricant",
    "Report hazards - to your supervisor or site safety personnel without delay": "Signaler les dangers a votre superviseur ou au personnel de securite sans delai",
    "Clean up your mess as soon as possible AND before end of every shift": "Nettoyer votre zone des que possible et avant la fin de chaque quart",
    "Correct unsafe conditions and report all incidents and injuries - regardless of severity": "Corriger les conditions dangereuses et signaler tous les incidents et blessures, peu importe la gravite",
    "Control and correct any hazard you create without delay": "Controler et corriger sans delai tout danger que vous creez",
    "Provide proof of training BEFORE conducting work that requires training or certification": "Fournir une preuve de formation AVANT le travail exigeant formation ou certification",
    "Respect the workplace by using the functioning washroom facilities": "Respecter le lieu de travail en utilisant les toilettes fonctionnelles",
    "Will you be doing traffic control on our site?": "Ferez-vous du controle de la circulation sur notre site?",
    "Do you have the following training or certifications:": "Avez-vous les formations ou certifications suivantes :",
    "WHMIS training (required by regulation)": "Formation SIMDUT (requise par la reglementation)",
    "Respirator fit tests": "Essais d'ajustement de respirateur",
    "Annual hearing tests": "Tests auditifs annuels",
    "Fall protection training?": "Formation protection contre les chutes?",
    "Confined space training?": "Formation espaces clos?",
    "Mobile Equipment training?": "Formation equipement mobile?",
    "Do you suffer / have you ever suffered from any form of heart or lung condition?":
      "Souffrez-vous ou avez-vous deja souffert d'une affection cardiaque ou pulmonaire?",
    "Do you have any allergies to food or drugs?": "Avez-vous des allergies alimentaires ou medicamenteuses?",
    "Do you suffer / have you ever suffered any chronic condition that could affect First Aid?":
      "Souffrez-vous ou avez-vous deja souffert d'une affection chronique pouvant affecter les premiers soins?",
    "Are you currently being prescribed any medication (please list)?":
      "Prenez-vous actuellement des medicaments prescrits (veuillez les indiquer)?",
    "Are you less than 25 years old or less than one year of experience in construction?":
      "Avez-vous moins de 25 ans ou moins d'un an d'experience en construction?",
    "Yes - stay after this orientation for additional info": "Oui - rester apres cette orientation pour plus d'information",
    "Have you received a New or Young Worker Orientation or training by your Employer?":
      "Avez-vous recu une orientation ou formation de nouveau ou jeune travailleur par votre employeur?",
    "Date of orientation by employer": "Date d'orientation par l'employeur",
    "I acknowledge that I will follow the above information. I understand my responsibilities for my health and safety on site. I also agree to participating in my Employer's Injury Management/Return to Work Program, and any other Health and Safety activities.":
      "Je reconnais que je suivrai les renseignements ci-dessus. Je comprends mes responsabilites pour ma sante et ma securite sur le site. J'accepte aussi de participer au programme de gestion des blessures/retour au travail de mon employeur et a toute autre activite de sante et securite.",
    "Worker's Name": "Nom du travailleur",
    "Worker Signature": "Signature du travailleur",
    "ORIENTATOR TO COMPLETE: I have reviewed the above workers information and it is complete.":
      "A COMPLETER PAR L'ORIENTATEUR : j'ai revise les renseignements du travailleur ci-dessus et ils sont complets.",
    "Orientator's provider": "Fournisseur de l'orientateur",
    "Orientator's Signature": "Signature de l'orientateur",
  },
  hi: {
    "Submitted Form": "जमा किया गया फॉर्म",
    "New Worker Orientation": "नए कर्मचारी का ओरिएंटेशन",
    "Toolbox Talk": "टूलबॉक्स सुरक्षा चर्चा",
    "Toolbox Talk Copy 2": "टूलबॉक्स सुरक्षा चर्चा कॉपी 2",
    "Site Inspection": "साइट निरीक्षण",
    "Staff Sign-Off": "स्टाफ साइन-ऑफ",
    "Not signed": "हस्ताक्षर नहीं हुए",
    "No staff sign-off recorded yet.": "अभी तक कोई स्टाफ साइन-ऑफ दर्ज नहीं है.",
    "Signed": "हस्ताक्षरित",
    "Comments": "टिप्पणियां",
    "Submitted": "जमा किया गया",
    "Phone": "फोन",
    "Username": "यूजरनेम",
    "Mode": "मोड",
    "Backup": "बैकअप",
    "Backup error": "बैकअप त्रुटि",
    "Open backup": "बैकअप खोलें",
    "Notes": "नोट्स",
    "Fill Form": "फॉर्म भरें",
    "Submit File": "फाइल जमा करें",
    "Backed up": "बैकअप हो गया",
    "Pending": "लंबित",
    "Failed": "विफल",
    "Unknown": "अज्ञात",
    "Reviewed": "समीक्षित",
    "Pending review": "समीक्षा लंबित",
    "Linked Action Items": "जुड़ी कार्रवाई वस्तुएं",
    "Action item": "कार्रवाई",
    "Unassigned": "असाइन नहीं",
    "Files": "फाइलें",
    "Opening...": "खोला जा रहा है...",
    "Opening": "खोला जा रहा है",
    "Open": "खोलें",
    "Attachment": "अटैचमेंट",
    "Preview": "पूर्वावलोकन",
    "Submitted file package": "जमा किया गया फाइल पैकेज",
    "No files uploaded": "कोई फाइल अपलोड नहीं हुई",
    "uploaded file": "अपलोड की गई फाइल",
    "uploaded files": "अपलोड की गई फाइलें",
    "was submitted as an uploaded attachment package.": "अपलोड किए गए अटैचमेंट पैकेज के रूप में जमा किया गया.",
    "File package summary": "फाइल पैकेज सारांश",
    "total": "कुल",
    "Image": "इमेज",
    "Document": "दस्तावेज",
    "Spreadsheet": "स्प्रेडशीट",
    "PDF": "PDF",
    "File": "फाइल",
    "Backup:": "बैकअप:",

    "Meeting Info": "मीटिंग जानकारी",
    "Project": "प्रोजेक्ट",
    "Address": "पता",
    "Date": "तारीख",
    "Time": "समय",
    "Presenter": "प्रस्तुतकर्ता",
    "Supervisor": "सुपरवाइजर",
    "Topics": "विषय",
    "Topics Discussed": "चर्चित विषय",
    "Review Notes": "समीक्षा नोट्स",
    "Safety Concerns": "सुरक्षा चिंताएं",
    "Attendance": "उपस्थिति",
    "Final Check": "अंतिम जांच",
    "Confirmed by": "पुष्टि करने वाला",
    "Confirmation date": "पुष्टि तारीख",
    "Participation confirmed": "भागीदारी की पुष्टि",
    "Yes": "हां",
    "No": "नहीं",
    "attendee": "उपस्थित व्यक्ति",
    "attendees": "उपस्थित लोग",
    "Identification": "पहचान",
    "General Safety": "सामान्य सुरक्षा",
    "PPE": "PPE",
    "Fall Protection": "फॉल प्रोटेक्शन",
    "Equipment": "उपकरण",
    "First Aid": "प्राथमिक उपचार",

    "Inspection Info": "निरीक्षण जानकारी",
    "Area": "क्षेत्र",
    "Inspector": "निरीक्षक",
    "Trades": "ट्रेड्स",
    "Reviewer": "समीक्षक",
    "Observations": "निरीक्षण टिप्पणियां",
    "Positive": "सकारात्मक",
    "High-risk work": "उच्च जोखिम वाला काम",
    "Immediate controls": "तत्काल नियंत्रण",
    "Follow-up": "फॉलो-अप",
    "Deficiencies": "कमियां",
    "No deficiencies found during this inspection.": "इस निरीक्षण में कोई कमी नहीं मिली.",
    "No deficiencies recorded.": "कोई कमी दर्ज नहीं है.",
    "Deficiency": "कमी",
    "Category": "श्रेणी",
    "Location": "स्थान",
    "Immediate control": "तत्काल नियंत्रण",
    "Corrective action": "सुधारात्मक कार्रवाई",
    "Assignee": "जिम्मेदार व्यक्ति",
    "Due": "देय",

    "NEW WORKER ORIENTATION": "नए कर्मचारी का ओरिएंटेशन",
    "ORIENTATION #": "ओरिएंटेशन #",
    "Orientation #": "ओरिएंटेशन #",
    "Worker Name": "कर्मचारी का नाम",
    "WORKER NAME": "कर्मचारी का नाम",
    "Telephone Number": "टेलीफोन नंबर",
    "TELEPHONE NUMBER": "टेलीफोन नंबर",
    "Company and Sub-Trade": "कंपनी और सब-ट्रेड",
    "COMPANY AND SUB-TRADE": "कंपनी और सब-ट्रेड",
    "Occupation": "पेशा",
    "OCCUPATION": "पेशा",
    "Supervisor Name": "सुपरवाइजर का नाम",
    "SUPERVISOR NAME": "सुपरवाइजर का नाम",
    "Supervisor Telephone": "सुपरवाइजर फोन",
    "SUPERVISOR TELEPHONE": "सुपरवाइजर फोन",
    "Emergency Contact Information": "आपातकालीन संपर्क जानकारी",
    "Emergency Contact Name": "आपातकालीन संपर्क नाम",
    "Relationship": "संबंध",
    "Paper Orientation Images": "पेपर ओरिएंटेशन इमेज",
    "Muster Station": "मस्टर स्टेशन",
    "Before and during your work on our site you must meet, and comply with, all company and WorkSafeBC requirements. Review and initial each section below. Ensure you understand and follow all company rules and OHS Regulations. The items with an * will have continual competency observations.":
      "हमारी साइट पर काम से पहले और दौरान आपको कंपनी और WorkSafeBC की सभी आवश्यकताओं का पालन करना होगा. नीचे हर सेक्शन की समीक्षा करें और इनिशियल करें. सुनिश्चित करें कि आप कंपनी के नियम और OHS नियम समझते और पालन करते हैं. * वाले आइटम पर लगातार योग्यता निरीक्षण होंगे.",
    "1 - SITE SAFETY AND EMERGENCY PROCEDURES": "1 - साइट सुरक्षा और आपातकालीन प्रक्रियाएं",
    "2 - POTENTIAL HAZARDS AND RESPONSIBILITIES": "2 - संभावित खतरे और जिम्मेदारियां",
    "3 - PERSONAL PROTECTIVE EQUIPMENT": "3 - व्यक्तिगत सुरक्षा उपकरण",
    "4 - WORKPLACE SAFETY RULES AND INFORMATION": "4 - कार्यस्थल सुरक्षा नियम और जानकारी",
    "5 - TRAFFIC CONTROL": "5 - ट्रैफिक कंट्रोल",
    "TRAFFIC CONTROL": "ट्रैफिक कंट्रोल",
    "6 - RIGHTS AND RESPONSIBILITIES": "6 - अधिकार और जिम्मेदारियां",
    "7 - TRAINING AND CERTIFICATIONS": "7 - प्रशिक्षण और प्रमाणपत्र",
    "8 - MEDICAL INFORMATION (Optional) - kept confidential and only provided to EMS if needed":
      "8 - चिकित्सा जानकारी (वैकल्पिक) - गोपनीय रखी जाती है और जरूरत होने पर ही EMS को दी जाती है",
    "Trade Orientation Confirmation": "ट्रेड ओरिएंटेशन पुष्टि",
    "9 - WORKER ACKNOWLEDGMENT": "9 - कर्मचारी स्वीकृति",
    "Appia's Health and Safety policy": "Appia की स्वास्थ्य और सुरक्षा नीति",
    "Location of First Aid facilities and our FA attendants": "प्राथमिक उपचार सुविधाओं और FA अटेंडेंट का स्थान",
    "How to report illness and injury without delay": "बीमारी और चोट की तुरंत रिपोर्ट कैसे करें",
    "Emergency procedures & muster station": "आपातकालीन प्रक्रियाएं और मस्टर स्टेशन",
    "Air horns and Fire extinguishers (Located on every level)": "एयर हॉर्न और अग्निशामक (हर स्तर पर स्थित)",
    "Access and egress route clear of obstructions and hazards": "प्रवेश और निकास मार्ग बाधाओं और खतरों से साफ",
    "Duty to report hazards, incidents, near misses & unsafe acts": "खतरों, घटनाओं, निकट चूक और असुरक्षित कार्यों की रिपोर्ट करने का कर्तव्य",
    "Accident/Incident investigations and reporting procedures": "दुर्घटना/घटना जांच और रिपोर्टिंग प्रक्रियाएं",
    "Housekeeping: ensure work area is clean at end of day": "हाउसकीपिंग: दिन के अंत में कार्य क्षेत्र साफ हो",
    "Working alone or in isolation": "अकेले या अलगाव में काम",
    "Bullying, harassment, threats, and violence- how to report": "बुलिंग, उत्पीड़न, धमकी और हिंसा - कैसे रिपोर्ट करें",
    "Theft and vandalism": "चोरी और तोड़फोड़",
    "Alcohol, drugs & impairment": "शराब, ड्रग्स और अक्षमता",
    "Stress, Excessive workload, mentally fit for work": "तनाव, अत्यधिक काम और काम के लिए मानसिक रूप से फिट",
    "SDS location, purpose, and key info on SDS and spill clean up": "SDS स्थान, उद्देश्य और SDS तथा स्पिल सफाई की मुख्य जानकारी",
    "Acceptable standards: CSA & ANSI": "स्वीकार्य मानक: CSA और ANSI",
    "Required PPE: Hard hat, safety boots & hi-visibility clothing": "आवश्यक PPE: हार्ड हैट, सुरक्षा बूट और हाई-विजिबिलिटी कपड़े",
    "Required Clothing: Long pants and shirt with sleeves": "आवश्यक कपड़े: लंबी पैंट और बाजू वाली शर्ट",
    "PPE fitting, Inspection & replacement": "PPE फिटिंग, निरीक्षण और बदलना",
    "Specialized PPE is provided by your employer": "विशेष PPE आपका नियोक्ता प्रदान करता है",
    "Follow manufacturer's instructions, SWP and SJP": "निर्माता के निर्देश, SWP और SJP का पालन करें",
    "Hearing Conservation Program": "श्रवण संरक्षण कार्यक्रम",
    "Respiratory Protection Program": "श्वसन सुरक्षा कार्यक्रम",
    "Site rules (and where to find them)": "साइट नियम (और उन्हें कहां ढूंढें)",
    "Disciplinary policy": "अनुशासन नीति",
    "Reviewing safe job procedures and safe work practices": "सुरक्षित कार्य प्रक्रियाओं और अभ्यासों की समीक्षा",
    "Public interactions and radio etiquette": "जनता से बातचीत और रेडियो शिष्टाचार",
    "Worker Health and Safety Representative(s) and JOHS Committee": "कर्मचारी स्वास्थ्य और सुरक्षा प्रतिनिधि और JOHS समिति",
    "Toolbox/safety meeting and safety committees": "टूलबॉक्स/सुरक्षा बैठक और सुरक्षा समितियां",
    "Compliance with OHS Program, basics of what is in it": "OHS प्रोग्राम का पालन और उसमें क्या है इसकी मूल बातें",
    "Location of WSBC regulations, OHS Program": "WSBC नियम और OHS प्रोग्राम का स्थान",
    "Traffic (city and WSBC) and Noise Bylaw": "ट्रैफिक (शहर और WSBC) और शोर उपनियम",
    "Daily Hazard Assessment is completed prior to work": "काम से पहले दैनिक खतरा आकलन पूरा किया जाता है",
    "Safe standing location & escape route identified/reviewed": "सुरक्षित खड़े होने की जगह और बचाव मार्ग पहचाना/समीक्षित",
    "TCP's with appropriate PPE for the task": "कार्य के लिए उचित PPE वाले TCP",
    "WORKER RIGHT TO:": "कर्मचारी का अधिकार:",
    "REFUSE unsafe work (that could affect the health and safety of you and others)": "असुरक्षित काम से मना करना (जो आपकी या दूसरों की स्वास्थ्य और सुरक्षा को प्रभावित कर सकता है)",
    "KNOW workplace hazards and controls (as discussed in this orientation and while on the job)": "कार्यस्थल के खतरे और नियंत्रण जानना (जैसा इस ओरिएंटेशन और काम पर बताया गया है)",
    "PARTICIPATE in health and safety activities (ex. Reporting unsafe acts or participating in the JOHS committee)": "स्वास्थ्य और सुरक्षा गतिविधियों में भाग लेना (जैसे असुरक्षित कार्य रिपोर्ट करना या JOHS समिति में भाग लेना)",
    "BE SUPERVISED by a competent supervisor": "योग्य सुपरवाइजर द्वारा निगरानी में रहना",
    "YOU ARE RESPONSIBLE TO:": "आपकी जिम्मेदारी है:",
    "Work safely and follow the Site Safety Rules": "सुरक्षित काम करें और साइट सुरक्षा नियमों का पालन करें",
    "Participate in, follow, and sign the Daily Hazard Assessment (FLRA/DHA/PSHA) as directed by your Supervisor": "अपने सुपरवाइजर के निर्देश अनुसार दैनिक खतरा आकलन (FLRA/DHA/PSHA) में भाग लें, पालन करें और हस्ताक्षर करें",
    "Use equipment you're competent and authorized to use, as per Manufacturer's Instructions": "निर्माता के निर्देश अनुसार वही उपकरण उपयोग करें जिसके लिए आप सक्षम और अधिकृत हैं",
    "Report hazards - to your supervisor or site safety personnel without delay": "खतरों को बिना देरी सुपरवाइजर या साइट सुरक्षा कर्मियों को रिपोर्ट करें",
    "Clean up your mess as soon as possible AND before end of every shift": "अपना क्षेत्र जल्द से जल्द और हर शिफ्ट खत्म होने से पहले साफ करें",
    "Correct unsafe conditions and report all incidents and injuries - regardless of severity": "असुरक्षित स्थितियां सुधारें और सभी घटनाओं व चोटों की रिपोर्ट करें, गंभीरता चाहे जो भी हो",
    "Control and correct any hazard you create without delay": "आप जो खतरा पैदा करते हैं उसे बिना देरी नियंत्रित और ठीक करें",
    "Provide proof of training BEFORE conducting work that requires training or certification": "जिस काम के लिए प्रशिक्षण या प्रमाणपत्र चाहिए, उसे करने से पहले प्रशिक्षण का प्रमाण दें",
    "Respect the workplace by using the functioning washroom facilities": "चलती वॉशरूम सुविधाओं का उपयोग करके कार्यस्थल का सम्मान करें",
    "Will you be doing traffic control on our site?": "क्या आप हमारी साइट पर ट्रैफिक कंट्रोल करेंगे?",
    "Do you have the following training or certifications:": "क्या आपके पास ये प्रशिक्षण या प्रमाणपत्र हैं:",
    "WHMIS training (required by regulation)": "WHMIS प्रशिक्षण (नियम से आवश्यक)",
    "Respirator fit tests": "रेस्पिरेटर फिट टेस्ट",
    "Annual hearing tests": "वार्षिक सुनवाई परीक्षण",
    "Fall protection training?": "फॉल प्रोटेक्शन प्रशिक्षण?",
    "Confined space training?": "कन्फाइंड स्पेस प्रशिक्षण?",
    "Mobile Equipment training?": "मोबाइल उपकरण प्रशिक्षण?",
    "Do you suffer / have you ever suffered from any form of heart or lung condition?":
      "क्या आपको या कभी कोई हृदय या फेफड़ों की स्थिति रही है?",
    "Do you have any allergies to food or drugs?": "क्या आपको भोजन या दवाओं से एलर्जी है?",
    "Do you suffer / have you ever suffered any chronic condition that could affect First Aid?":
      "क्या आपको कोई ऐसी पुरानी स्थिति है या रही है जो प्राथमिक उपचार को प्रभावित कर सकती है?",
    "Are you currently being prescribed any medication (please list)?":
      "क्या आपको अभी कोई दवा लिखी गई है (कृपया लिखें)?",
    "Are you less than 25 years old or less than one year of experience in construction?":
      "क्या आपकी उम्र 25 से कम है या निर्माण में एक साल से कम अनुभव है?",
    "Yes - stay after this orientation for additional info": "हां - अतिरिक्त जानकारी के लिए इस ओरिएंटेशन के बाद रुकें",
    "Have you received a New or Young Worker Orientation or training by your Employer?":
      "क्या आपको अपने नियोक्ता से नया या युवा कर्मचारी ओरिएंटेशन या प्रशिक्षण मिला है?",
    "Date of orientation by employer": "नियोक्ता द्वारा ओरिएंटेशन की तारीख",
    "I acknowledge that I will follow the above information. I understand my responsibilities for my health and safety on site. I also agree to participating in my Employer's Injury Management/Return to Work Program, and any other Health and Safety activities.":
      "मैं स्वीकार करता/करती हूं कि मैं ऊपर की जानकारी का पालन करूंगा/करूंगी. मैं साइट पर अपनी स्वास्थ्य और सुरक्षा जिम्मेदारियां समझता/समझती हूं. मैं अपने नियोक्ता के चोट प्रबंधन/काम पर वापसी कार्यक्रम और अन्य स्वास्थ्य व सुरक्षा गतिविधियों में भाग लेने के लिए भी सहमत हूं.",
    "Worker's Name": "कर्मचारी का नाम",
    "Worker Signature": "कर्मचारी हस्ताक्षर",
    "ORIENTATOR TO COMPLETE: I have reviewed the above workers information and it is complete.":
      "ओरिएंटेटर द्वारा पूरा करें: मैंने ऊपर दी गई कर्मचारी जानकारी की समीक्षा की है और यह पूरी है.",
    "Orientator's provider": "ओरिएंटेटर प्रदाता",
    "Orientator's Signature": "ओरिएंटेटर हस्ताक्षर",
  },
};

const PHRASEBOOKS = Object.fromEntries(
  Object.entries(RAW_PHRASEBOOKS).map(([language, entries]) => [language, makePhrasebook(entries)]),
);

export function translateSubmittedFormTexts(languageCode, texts = []) {
  const language = SUBMITTED_FORM_TRANSLATION_LANGUAGES.find((item) => item.code === languageCode);
  const phrasebook = PHRASEBOOKS[languageCode] || {};
  const translations = [];
  const seen = new Set();

  texts.forEach((text) => {
    const source = normalizePhrasebookText(text);
    if (!source || seen.has(source)) return;
    seen.add(source);
    const translated = translateSubmittedFormText(source, phrasebook);
    if (!translated || translated === source) return;
    translations.push({ source, text: translated });
  });

  return {
    language: language?.code || languageCode,
    languageLabel: language?.label || languageCode,
    translatedCount: translations.length,
    translations,
  };
}

function makePhrasebook(entries) {
  return Object.fromEntries(
    Object.entries(entries).map(([source, translated]) => [normalizePhrasebookKey(source), translated]),
  );
}

function translateSubmittedFormText(source, phrasebook) {
  const exact = lookupPhrase(phrasebook, source);
  if (exact) return exact;

  const fileCountMatch = source.match(/^(\d+)\s+uploaded\s+(file|files)$/i);
  if (fileCountMatch) {
    const noun = lookupPhrase(phrasebook, fileCountMatch[2].toLowerCase());
    return noun ? `${fileCountMatch[1]} ${noun}` : "";
  }

  const totalSizeMatch = source.match(/^(.+)\s+total$/i);
  if (totalSizeMatch) {
    const total = lookupPhrase(phrasebook, "total");
    return total ? `${totalSizeMatch[1]} ${total}` : "";
  }

  const filePackageMatch = source.match(/^(.+)\s+was submitted as an uploaded attachment package\.$/i);
  if (filePackageMatch) {
    const formName = translateSubmittedFormText(filePackageMatch[1], phrasebook) || filePackageMatch[1];
    const suffix = lookupPhrase(phrasebook, "was submitted as an uploaded attachment package.");
    return suffix ? `${formName} ${suffix}` : "";
  }

  const attendeeCountMatch = source.match(/^(\d+)\s+(attendee|attendees)$/i);
  if (attendeeCountMatch) {
    const noun = lookupPhrase(phrasebook, attendeeCountMatch[2].toLowerCase());
    return noun ? `${attendeeCountMatch[1]} ${noun}` : "";
  }

  const slashTranslation = translateDelimitedText(source, phrasebook, " / ");
  if (slashTranslation) return slashTranslation;

  const dashTranslation = translateDelimitedText(source, phrasebook, " - ");
  if (dashTranslation) return dashTranslation;

  return translateLabelValue(source, phrasebook);
}

function translateDelimitedText(source, phrasebook, delimiter) {
  if (!source.includes(delimiter)) return "";
  const pieces = source.split(delimiter);
  const translatedPieces = pieces.map((piece) => translateSubmittedFormText(piece, phrasebook) || piece);
  return translatedPieces.some((piece, index) => piece !== pieces[index])
    ? translatedPieces.join(delimiter)
    : "";
}

function translateLabelValue(source, phrasebook) {
  const labelMatch = source.match(/^([^:]+):\s*(.*)$/);
  if (!labelMatch) return "";
  const translatedLabel = lookupPhrase(phrasebook, `${labelMatch[1]}:`) || lookupPhrase(phrasebook, labelMatch[1]);
  if (!translatedLabel) return "";
  const value = labelMatch[2];
  const translatedValue = translateSubmittedFormText(value, phrasebook) || value;
  const separator = translatedLabel.endsWith(":") || translatedLabel.endsWith("：") ? " " : ": ";
  return `${translatedLabel}${separator}${translatedValue}`;
}

function lookupPhrase(phrasebook, source) {
  return phrasebook[normalizePhrasebookKey(source)] || "";
}

function normalizePhrasebookText(value) {
  return String(value || "")
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/\s+/g, " ")
    .trim();
}

function normalizePhrasebookKey(value) {
  return normalizePhrasebookText(value).toLowerCase();
}
