export const maturityLevels = [
  "Draft",
  "Source checked",
  "Safety reviewed",
  "Ready for public use",
  "Needs update",
];

export const tierOneArticleSlugs = [
  "fall-protection",
  "fall-protection-plan",
  "fall-arrest",
  "guardrails",
  "silica-exposure-control",
  "respirators",
  "asbestos-basics",
  "excavation-and-trenching",
  "confined-space-entry",
  "confined-space-rescue",
  "cranes-and-hoists",
  "rigging-basics",
  "electrical-safety-near-power-lines",
  "occupational-first-aid-requirements",
  "traffic-control",
];

export const tierTwoArticleSlugs = [
  "ppe-basics",
  "ladders",
  "scaffolds",
  "hot-work",
  "housekeeping",
  "site-orientation",
  "workplace-inspections",
  "mobile-equipment",
  "lockout",
  "demolition-planning",
  "site-emergency-response-plan",
  "first-aid-assessment",
  "traffic-control-plans",
  "traffic-control-persons",
];

export const articleWorkflow = Object.fromEntries([
  ...tierOneArticleSlugs.map((slug) => [
    slug,
    {
      reviewTier: "Tier 1",
      maturity: "Draft",
      reviewPriority: "High-risk legal/source hardening",
    },
  ]),
  ...tierTwoArticleSlugs.map((slug) => [
    slug,
    {
      reviewTier: "Tier 2",
      maturity: "Draft",
      reviewPriority: "Common field-use review",
    },
  ]),
]);

const baseWikiRedirects = [
  { from: "tie-off", term: "tie off", to: "fall-protection" },
  { from: "tie-off-plan", term: "tie off plan", to: "fall-protection-plan" },
  { from: "hole-cover", term: "hole cover", to: "floor-openings-and-covers" },
  { from: "floor-hole", term: "floor hole", to: "floor-openings-and-covers" },
  { from: "dust-mask", term: "dust mask", to: "respirators" },
  { from: "mask-fit-test", term: "mask fit test", to: "respirators" },
  { from: "toolbox-talk", term: "toolbox talk", to: "toolbox-talks" },
  { from: "tailgate-meeting", term: "tailgate meeting", to: "toolbox-talks" },
  { from: "silica-dust", term: "silica dust", to: "silica-exposure-control" },
  { from: "concrete-dust", term: "concrete dust", to: "silica-exposure-control" },
  { from: "crane-pick", term: "crane pick", to: "cranes-and-hoists" },
  { from: "pick-plan", term: "pick plan", to: "lift-plans" },
  { from: "first-aid-room", term: "first aid room", to: "first-aid-room" },
  { from: "fall-rescue", term: "fall rescue", to: "fall-rescue-plan" },
  { from: "confined-space-permit", term: "confined space permit", to: "confined-space-entry" },
  { from: "entry-permit", term: "entry permit", to: "confined-space-entry" },
  { from: "power-line", term: "power line", to: "electrical-safety-near-power-lines" },
  { from: "30m33", term: "30M33", to: "electrical-safety-near-power-lines" },
];

const workerLanguageRedirects = [
  ["working at heights", "fall-protection"],
  ["edge protection", "guardrails"],
  ["open edge", "leading-edge-work"],
  ["deck edge", "leading-edge-work"],
  ["shaft opening", "floor-openings-and-covers"],
  ["fall restraint", "fall-restraint"],
  ["travel restraint", "fall-restraint"],
  ["harness", "fall-arrest"],
  ["full body harness", "fall-arrest"],
  ["lanyard", "fall-arrest"],
  ["self retracting lifeline", "fall-arrest"],
  ["srl", "fall-arrest"],
  ["tie off point", "anchor-points"],
  ["roof anchor", "anchor-points"],
  ["anchorage", "anchor-points"],
  ["suspension trauma", "suspension-trauma"],
  ["harness trauma", "suspension-trauma"],
  ["roofing", "roof-work"],
  ["swing stage", "swing-stages"],
  ["suspended scaffold", "swing-stages"],
  ["rope access", "rope-access"],
  ["bosun chair", "rope-access"],
  ["temporary work platform", "work-platforms"],
  ["work platform", "work-platforms"],
  ["scissor lift", "mobile-elevating-work-platforms"],
  ["boom lift", "mobile-elevating-work-platforms"],
  ["mewp", "mobile-elevating-work-platforms"],
  ["manlift", "mobile-elevating-work-platforms"],
  ["step ladder", "ladders"],
  ["extension ladder", "ladders"],
  ["ladder checklist", "ladder-inspection"],
  ["ladder pre-use", "ladder-inspection"],
  ["frame scaffold", "scaffolds"],
  ["scaffold tag", "scaffold-inspection"],
  ["scaffold checklist", "scaffold-inspection"],
  ["flyforms", "concrete-formwork"],
  ["flytable", "concrete-formwork"],
  ["reshoring", "falsework"],
  ["temporary supports", "falsework"],
  ["pump truck", "concrete-pumping"],
  ["boom pump", "concrete-pumping"],
  ["hose whip", "concrete-pumping"],
  ["rebar caps", "rebar-impalement-protection"],
  ["impalement hazard", "rebar-impalement-protection"],
  ["tilt-up", "tilt-up-construction"],
  ["tilt wall", "tilt-up-construction"],
  ["demo plan", "demolition-planning"],
  ["strip-out", "demolition-planning"],
  ["hazmat survey", "hazardous-materials-before-demolition"],
  ["hazardous materials survey", "hazardous-materials-before-demolition"],
  ["asbestos", "asbestos-basics"],
  ["acm", "asbestos-basics"],
  ["lead paint", "lead-exposure-control"],
  ["lead dust", "lead-exposure-control"],
  ["mould", "mould-in-restoration"],
  ["mold", "mould-in-restoration"],
  ["water damage", "mould-in-restoration"],
  ["construction noise", "noise-exposure"],
  ["noise survey", "noise-exposure"],
  ["ear plugs", "hearing-protection"],
  ["ear muffs", "hearing-protection"],
  ["heat stress", "heat-stress"],
  ["heat illness", "heat-stress"],
  ["cold stress", "cold-stress"],
  ["hypothermia", "cold-stress"],
  ["carbon monoxide", "carbon-monoxide"],
  ["co", "carbon-monoxide"],
  ["generator fumes", "carbon-monoxide"],
  ["local exhaust", "ventilation"],
  ["negative air", "ventilation"],
  ["dust extraction", "dust-control-methods"],
  ["hepa vacuum", "hepa-vacuums"],
  ["wet methods", "wet-cutting"],
  ["wet saw", "wet-cutting"],
  ["wet cutting", "wet-cutting"],
  ["slurry control", "wet-cutting"],
  ["dust extractor", "hepa-vacuums"],
  ["tool shroud", "hepa-vacuums"],
  ["clean up", "housekeeping"],
  ["trip hazards", "housekeeping"],
  ["ppe", "ppe-basics"],
  ["safety gear", "ppe-basics"],
  ["hard hat", "hard-hats"],
  ["safety headgear", "hard-hats"],
  ["safety glasses", "eye-and-face-protection"],
  ["face shield", "eye-and-face-protection"],
  ["hi-vis", "high-visibility-apparel"],
  ["safety vest", "high-visibility-apparel"],
  ["safety boots", "safety-footwear"],
  ["steel toes", "safety-footwear"],
  ["work gloves", "gloves"],
  ["cut resistant gloves", "gloves"],
  ["loto", "lockout"],
  ["lock out", "lockout"],
  ["personal lock", "lockout"],
  ["zero energy", "de-energization"],
  ["test before touch", "de-energization"],
  ["temp power", "temporary-power"],
  ["gfci", "temporary-power"],
  ["extension cords", "temporary-power"],
  ["angle grinder", "power-tools"],
  ["portable power tools", "power-tools"],
  ["hilti gun", "powder-actuated-tools"],
  ["ramset", "powder-actuated-tools"],
  ["powder tool", "powder-actuated-tools"],
  ["torch cutting", "welding-and-cutting"],
  ["arc welding", "welding-and-cutting"],
  ["oxygen cylinders", "compressed-gas-cylinders"],
  ["acetylene", "compressed-gas-cylinders"],
  ["safe lifting", "material-handling"],
  ["material storage", "material-handling"],
  ["site fence", "hoarding-and-public-protection"],
  ["pedestrian protection", "hoarding-and-public-protection"],
  ["flagger", "traffic-control-persons"],
  ["traffic control person", "traffic-control-persons"],
  ["tcp", "traffic-control-persons"],
  ["lane closure plan", "traffic-control-plans"],
  ["traffic management plan", "traffic-control-plans"],
  ["trench", "excavation-and-trenching"],
  ["spoil pile", "excavation-spoil-piles"],
  ["surcharge load", "excavation-spoil-piles"],
  ["bc 1 call", "underground-utilities"],
  ["utility locates", "underground-utilities"],
  ["underground services", "underground-utilities"],
  ["crane power lines", "cranes-near-power-lines"],
  ["plan for 10", "cranes-near-power-lines"],
  ["critical lift plan", "lift-plans"],
  ["signal person", "crane-operator-signaller-responsibilities"],
  ["hand signals", "crane-operator-signaller-responsibilities"],
  ["site induction", "site-orientation"],
  ["safety orientation", "site-orientation"],
  ["new worker", "young-new-worker-orientation"],
  ["young worker", "young-new-worker-orientation"],
  ["near miss", "incident-investigation"],
  ["incident report", "incident-investigation"],
  ["corrective action", "corrective-actions"],
  ["deficiency", "corrective-actions"],
  ["safety program", "ohs-program"],
  ["sssp", "site-specific-safety-plan"],
  ["project safety plan", "site-specific-safety-plan"],
  ["training record", "training-records"],
  ["ticket record", "training-records"],
  ["competency record", "training-records"],
  ["nop", "notice-of-project"],
  ["notice to worksafebc", "notice-of-project"],
  ["preserve the scene", "serious-injury-reporting"],
  ["serious incident", "serious-injury-reporting"],
  ["ambulance access", "emergency-transportation"],
  ["transport plan", "emergency-transportation"],
  ["defibrillator", "aeds-on-construction-sites"],
  ["aed", "aeds-on-construction-sites"],
  ["heart attack", "cardiac-arrest-on-site"],
  ["emergency plan", "site-emergency-response-plan"],
  ["fire plan", "fire-prevention-plan"],
  ["fire safety plan", "fire-prevention-plan"],
  ["fire watch", "hot-work"],
  ["hot work permit", "hot-work"],
  ["extinguisher", "fire-extinguishers"],
  ["muster", "evacuation"],
  ["assembly area", "evacuation"],
  ["prime", "prime-contractor-duties"],
  ["site prime", "prime-contractor-duties"],
  ["foreman duties", "supervisor-duties"],
  ["worker rights", "worker-rights-and-responsibilities"],
  ["right to refuse", "refusal-of-unsafe-work"],
  ["unsafe work refusal", "refusal-of-unsafe-work"],
  ["safety committee", "jhsc-requirements"],
  ["johsc", "jhsc-requirements"],
  ["site inspection", "workplace-inspections"],
  ["walkthrough", "workplace-inspections"],
];

export const wikiRedirects = mergeRedirects([
  ...baseWikiRedirects,
  ...workerLanguageRedirects.map(([term, to]) => ({
    from: slugifyTerm(term),
    term,
    to,
  })),
]);

const baseGlossaryTerms = [
  {
    term: "competent person",
    slug: "competent-person",
    targetArticle: "supervisor-duties",
    definition:
      "A person who has enough training, experience, and knowledge of the work and hazards to carry out an assigned safety duty.",
  },
  {
    term: "qualified person",
    slug: "qualified-person",
    targetArticle: "supervisor-duties",
    definition:
      "A person whose education, training, experience, or professional status is suitable for the specific work or assessment being assigned.",
  },
  {
    term: "prime contractor",
    slug: "prime-contractor",
    targetArticle: "prime-contractor-duties",
    definition:
      "The party responsible for coordinating health and safety activities at a multiple-employer construction workplace.",
  },
  {
    term: "exposure control plan",
    slug: "exposure-control-plan",
    targetArticle: "silica-exposure-control",
    definition:
      "A written plan describing exposure hazards, controls, training, monitoring, and review for a hazardous substance or process.",
  },
  {
    term: "rescue plan",
    slug: "rescue-plan",
    targetArticle: "fall-rescue-plan",
    definition:
      "A planned method for summoning help, reaching a worker, controlling hazards, and moving the worker to first aid or medical care.",
  },
  {
    term: "safe work procedure",
    slug: "safe-work-procedure",
    targetArticle: "site-specific-safety-plan",
    definition:
      "A written procedure that tells workers how to do a task safely for the site conditions, hazards, equipment, and crew involved.",
  },
];

const additionalGlossaryTerms = [
  ["fall arrest", "fall-arrest", "A system intended to stop a worker after a fall has started, using compatible body support, connection, anchorage, clearance, inspection, and rescue planning."],
  ["fall restraint", "fall-restraint", "A fall protection method that keeps the worker from reaching the fall edge or opening."],
  ["anchor point", "anchor-points", "A point of attachment for a fall protection system that must be suitable for the intended load and use."],
  ["leading edge", "leading-edge-work", "An unprotected edge that moves or changes as construction progresses, such as decking, forming, roofing, or floor installation."],
  ["floor opening", "floor-openings-and-covers", "An opening in a floor, roof, deck, or work surface that can expose workers or materials to a fall."],
  ["guardrail", "guardrails", "A passive edge-protection system that separates workers from fall hazards."],
  ["suspension trauma", "suspension-trauma", "A medical emergency risk that can occur when a worker is suspended in a harness after a fall arrest."],
  ["rescue plan", "fall-rescue-plan", "A written and workable method for reaching, recovering, and transferring a worker after a fall or other emergency."],
  ["confined space", "confined-space-entry", "An enclosed or partially enclosed space that is not designed for continuous occupancy and may have serious atmospheric or physical hazards."],
  ["entry permit", "confined-space-entry", "A written confined-space entry authorization that documents conditions, controls, attendants, communication, and rescue arrangements."],
  ["standby person", "confined-space-entry", "A worker assigned to monitor entry conditions, maintain communication, and summon help for confined-space work."],
  ["atmospheric testing", "confined-space-entry", "Testing air for oxygen, flammable, toxic, or other hazardous conditions before and during entry where required."],
  ["exposure control plan", "silica-exposure-control", "A written plan describing exposure hazards, controls, training, monitoring, and review for a hazardous substance or process."],
  ["respirable crystalline silica", "silica-exposure-control", "Fine silica-containing dust that can be inhaled deep into the lungs during tasks such as cutting, grinding, drilling, or crushing concrete and rock."],
  ["HEPA vacuum", "hepa-vacuums", "A vacuum fitted with high-efficiency filtration and used as part of a dust-control or cleanup method."],
  ["wet cutting", "wet-cutting", "A dust-control method that applies water at the point of cutting or grinding to reduce airborne dust."],
  ["respirator fit test", "respirators", "A test used to confirm a tight-fitting respirator can seal properly to the worker's face."],
  ["SDS", "whmis-basics", "A safety data sheet that provides hazard, handling, storage, emergency, and control information for a hazardous product."],
  ["WHMIS", "whmis-basics", "Canada's workplace hazardous product information system for labels, safety data sheets, and worker education."],
  ["lockout", "lockout", "A method of controlling hazardous energy by isolating equipment and applying personal locks before work is done."],
  ["de-energization", "de-energization", "Removing hazardous energy from equipment or conductors before work proceeds."],
  ["zero energy", "de-energization", "The condition where stored, residual, or supplied energy has been controlled so equipment cannot move, start, release, or shock unexpectedly."],
  ["GFCI", "temporary-power", "A ground-fault circuit interrupter used to reduce electric shock risk from temporary power and portable tools."],
  ["hot work", "hot-work", "Work such as welding, cutting, grinding, torching, or similar activity that can create ignition sources."],
  ["fire watch", "hot-work", "A worker assigned to monitor hot work and surrounding areas for ignition, fire, and required follow-up time."],
  ["muster area", "evacuation", "The designated place workers report to during an evacuation or emergency headcount."],
  ["AED", "aeds-on-construction-sites", "An automated external defibrillator used by trained responders or under emergency direction during suspected cardiac arrest."],
  ["occupational first aid", "occupational-first-aid-requirements", "The first aid services, supplies, attendants, procedures, communication, and transportation arranged for a workplace."],
  ["first aid assessment", "first-aid-assessment", "The documented review used to decide first aid services, equipment, attendants, facilities, communication, and transport arrangements."],
  ["traffic control person", "traffic-control-persons", "A trained person who controls traffic and protects workers, road users, and pedestrians near work activity."],
  ["traffic control plan", "traffic-control-plans", "A plan that sets out signs, devices, worker positions, routes, and control methods for traffic near work."],
  ["prime contractor", "prime-contractor-duties", "The party responsible for coordinating health and safety activities at a multiple-employer construction workplace."],
  ["supervisor", "supervisor-duties", "A person who instructs, directs, and controls workers and has duties to ensure work is done safely."],
  ["worker representative", "jhsc-requirements", "A worker selected to participate in workplace health and safety consultation when a committee is not required."],
  ["joint health and safety committee", "jhsc-requirements", "A worker-employer committee that helps identify hazards, review incidents, inspections, and make safety recommendations."],
  ["Notice of Project", "notice-of-project", "A notice submitted before specified construction or demolition work starts when WorkSafeBC requires project notification."],
  ["serious injury", "serious-injury-reporting", "A workplace injury or incident category that can require immediate reporting and scene protection."],
  ["corrective action", "corrective-actions", "A documented fix that assigns an owner and follow-up for a hazard, deficiency, incident cause, or inspection finding."],
  ["safe work procedure", "site-specific-safety-plan", "A written procedure that tells workers how to do a task safely for the site conditions, hazards, equipment, and crew involved."],
  ["site-specific safety plan", "site-specific-safety-plan", "The project safety plan that ties the employer, prime contractor, task controls, emergency procedures, and documentation together for one site."],
  ["toolbox talk", "toolbox-talks", "A short crew safety meeting focused on the work, hazards, controls, and questions for a task or condition."],
  ["new worker orientation", "young-new-worker-orientation", "Initial instruction and site familiarization for workers who are young, new to the workplace, or new to the task."],
  ["scaffold tag", "scaffold-inspection", "A field tag or marking system used to communicate scaffold inspection or use status."],
  ["mobile equipment", "mobile-equipment", "Self-propelled or towed equipment such as loaders, telehandlers, excavators, forklifts, skid steers, and similar site equipment."],
  ["lift plan", "lift-plans", "A plan that describes the load, equipment, rigging, people, route, limits, communication, and controls for a hoisting operation."],
  ["signal person", "crane-operator-signaller-responsibilities", "A person assigned to communicate movement instructions to a crane or hoist operator."],
  ["rigging", "rigging-basics", "The selection and use of slings, hardware, hitches, and methods to connect and control a load."],
  ["underground utility locate", "underground-utilities", "A check and confirmation process for locating underground services before excavation or ground disturbance."],
  ["spoil pile", "excavation-spoil-piles", "Excavated material placed near a trench or excavation that can create surcharge, access, or cave-in hazards."],
  ["hoarding", "hoarding-and-public-protection", "Temporary fencing, walls, overhead protection, or barriers used to separate the public from construction hazards."],
  ["high-visibility apparel", "high-visibility-apparel", "Clothing designed to make workers easier to see around traffic, mobile equipment, and low-visibility conditions."],
  ["powder-actuated tool", "powder-actuated-tools", "A tool that uses an explosive charge to drive fasteners into hard material and requires controlled use and instruction."],
  ["compressed gas cylinder", "compressed-gas-cylinders", "A pressure vessel holding gas such as oxygen, acetylene, propane, nitrogen, or shielding gas for site use."],
  ["mould remediation", "mould-in-restoration", "Work that disturbs mould-contaminated materials and requires exposure control, containment, PPE, and cleanup planning."],
  ["carbon monoxide", "carbon-monoxide", "A toxic gas from combustion sources that can accumulate near heaters, generators, engines, or poorly ventilated areas."],
];

export const glossaryTerms = uniqueBySlug([
  ...baseGlossaryTerms,
  ...additionalGlossaryTerms.map(([term, targetArticle, definition]) => ({
    term,
    slug: slugifyTerm(term),
    targetArticle,
    definition,
  })),
]);

export const searchSuggestionTerms = [
  "tie off",
  "silica dust",
  "crane pick",
  "first aid room",
  "fall rescue",
  "confined space permit",
  "hole cover",
  "dust mask",
  "crane pick",
  "hot work permit",
  "first aid assessment",
  "site orientation",
  "lockout",
  "scaffold tag",
  "utility locates",
];

export const articleResourceLinks = {
  "fall-protection": {
    toolboxTalks: ["tie-off-planning-before-edge-work", "harness-inspection", "fall-rescue-readiness"],
    checklists: ["fall-protection"],
    quizzes: ["fall-protection-quiz"],
    forms: ["toolbox-talk-attendance", "training-matrix", "hazard-report"],
  },
  "fall-protection-plan": {
    toolboxTalks: ["tie-off-planning-before-edge-work", "fall-rescue-readiness"],
    checklists: ["fall-protection"],
    quizzes: ["fall-protection-quiz"],
    forms: ["toolbox-talk-attendance", "hazard-report"],
  },
  "fall-arrest": {
    toolboxTalks: ["harness-inspection", "fall-rescue-readiness"],
    checklists: ["fall-protection"],
    quizzes: ["fall-protection-quiz"],
    forms: ["equipment-inspection", "training-matrix"],
  },
  guardrails: {
    toolboxTalks: ["guardrails-and-floor-openings", "tie-off-planning-before-edge-work"],
    checklists: ["fall-protection", "daily-site-inspection"],
    quizzes: ["fall-protection-quiz"],
    forms: ["site-safety-inspection", "hazard-report"],
  },
  "silica-exposure-control": {
    toolboxTalks: ["silica-dust-controls", "wet-cutting-and-hepa-cleanup", "respirator-fit-and-seal-checks"],
    checklists: ["silica-dust"],
    quizzes: ["silica-and-dust-quiz"],
    forms: ["hazard-report", "training-matrix", "site-safety-inspection"],
  },
  respirators: {
    toolboxTalks: ["respirator-fit-and-seal-checks", "silica-dust-controls"],
    checklists: ["ppe", "silica-dust"],
    quizzes: ["ppe-quiz", "silica-and-dust-quiz"],
    forms: ["training-matrix", "equipment-inspection"],
  },
  "asbestos-basics": {
    toolboxTalks: ["whmis-labels-and-sds-access", "respirator-fit-and-seal-checks"],
    checklists: ["whmis-sds", "ppe"],
    quizzes: ["whmis-sds-quiz", "silica-and-dust-quiz"],
    forms: ["hazard-report", "training-matrix", "site-safety-inspection"],
  },
  "excavation-and-trenching": {
    toolboxTalks: ["trench-cave-in-warning-signs", "underground-utility-awareness"],
    checklists: ["excavations"],
    quizzes: ["excavation-and-trenching-quiz"],
    forms: ["hazard-report", "site-safety-inspection"],
  },
  "confined-space-entry": {
    toolboxTalks: ["confined-space-entry-basics", "atmospheric-testing-awareness"],
    checklists: ["confined-space-pre-entry"],
    quizzes: ["confined-spaces-quiz"],
    forms: ["hazard-report", "training-matrix"],
  },
  "confined-space-rescue": {
    toolboxTalks: ["confined-space-entry-basics", "atmospheric-testing-awareness"],
    checklists: ["confined-space-pre-entry", "emergency-response"],
    quizzes: ["confined-spaces-quiz", "emergency-response-quiz"],
    forms: ["hazard-report", "incident-report"],
  },
  "cranes-and-hoists": {
    toolboxTalks: ["crane-pick-communication", "exclusion-zones-under-suspended-loads"],
    checklists: ["mobile-equipment"],
    quizzes: ["cranes-rigging-quiz"],
    forms: ["equipment-inspection", "hazard-report"],
  },
  "rigging-basics": {
    toolboxTalks: ["rigging-inspection-basics", "exclusion-zones-under-suspended-loads"],
    checklists: ["mobile-equipment"],
    quizzes: ["cranes-rigging-quiz"],
    forms: ["equipment-inspection", "hazard-report"],
  },
  "electrical-safety-near-power-lines": {
    toolboxTalks: ["overhead-power-line-awareness", "extension-cords-and-temporary-power"],
    checklists: ["daily-site-inspection", "mobile-equipment"],
    quizzes: ["electrical-safety-quiz"],
    forms: ["hazard-report", "site-safety-inspection"],
  },
  "occupational-first-aid-requirements": {
    toolboxTalks: ["first-aid-access-and-reporting", "aed-location-and-emergency-access"],
    checklists: ["first-aid-kit-first-aid-room", "emergency-response"],
    quizzes: ["first-aid-quiz"],
    forms: ["incident-report", "near-miss-report"],
  },
  "traffic-control": {
    toolboxTalks: ["traffic-control-around-deliveries", "pedestrian-detours"],
    checklists: ["traffic-control"],
    quizzes: ["traffic-control-quiz"],
    forms: ["site-safety-inspection", "hazard-report"],
  },
};

export const reviewerChecklist = [
  "Legal citations checked against current WorkSafeBC/OHS source",
  "Wording does not overstate law or remove required judgement",
  "Best practice is separated from legal requirement",
  "Procedure is practical for BC construction field use",
  "Worker and supervisor checklists match the article content",
  "Related links, forms, toolbox talks, and quizzes are relevant",
  "No proprietary manual text or excessive source copying",
];

export function workflowForArticle(slug) {
  return articleWorkflow[slug] || {
    reviewTier: "Tier 3",
    maturity: "Draft",
    reviewPriority: "Support/reference review",
  };
}

function mergeRedirects(rows) {
  const seen = new Set();
  return rows.filter((row) => {
    const key = slugifyTerm(row.from);
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function uniqueBySlug(rows) {
  const seen = new Set();
  return rows.filter((row) => {
    if (seen.has(row.slug)) return false;
    seen.add(row.slug);
    return true;
  });
}

function slugifyTerm(value) {
  return String(value)
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
